### ISSUE TITLE
Main 3D view disappears after context loss

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#100]
Was fuzzing Molecule Shapes and lost context:

![molecule-shapes-lost-context](https://cloud.githubusercontent.com/assets/480878/6055731/b1b3e5f0-acc2-11e4-9d3e-dc8411542c54.png)

This could be a much larger problem on mobile devices.

**Comment by jonathanolson** [comment]
Migrated to three.js r70, allows us to do the following to test context loss:
```
phet.joist.display.rootNode.children[1].threeRenderer.forceContextLoss()
```

I tested, and it seems to have the same behavior as the context loss, but without printing the same context loss warning in the console that Chrome did on its own.

**Comment by jonathanolson** [comment]
Looks like the forceContextLoss() doesn't trigger any of the context loss listeners. Manually triggered it (opened 5 copies of Molecule Shapes, tabbed out, and launched a few intensive 3D games), and the listeners were successfully triggered. I'll probably need to do that to test.

Also r70 has a context loss listener that prevents default already.

**Comment by samreid** [comment]
How does three.js have `forceContextLoss`?  I thought that was typically done with the khronos webgl-debug.js wrapper, which incurs extra overhead and can slow things down.  Just asking since I didn't know whether three.js included the webgl-debug file or if you had to supply it somewhere.

**Comment by jonathanolson** [comment]
In the relevant issue (https://github.com/mrdoob/three.js/issues/5507), they note there's a WebGL extension for this:
```js
context.getExtension( 'WEBGL_lose_context' ).loseContext();
```
Seems much more convenient than completely modifying/overriding the Canvas prototype.

**Comment by jonathanolson** [comment]
Looks like I'll have to revert to r68 on three.js, CanvasRenderer was removed (https://github.com/mrdoob/three.js/issues/5724).

I almost celebrated, because:
> The reason was because WebGL is now supported everywhere.

but realized 'everywhere' probably means something different.

**Comment by jonathanolson** [comment]
I'd like to get @ariel-phet's opinion on the priority for this. Would it be OK to detect this condition (which can happen if the computer/device runs out of graphics memory and has to ditch our part, or when the graphics card gets fully reset) and just display a dialog noting that they'd need to restart the sim?

We can't immediately recreate the view with WebGL. Three.js is inhibiting the default way of bringing back the context, and doesn't support recovery after the loss.

It would require decent refactoring to allow the sim to switch immediately into Canvas mode (I have code that does the switch, but many parts of the sim assume we don't switch between Canvas/WebGL). Is that preferred?

**Comment by samreid** [comment]
Can't you wait until the context is restored, then recreate all of the simulation views (from the same models)?

**Comment by jonathanolson** [comment]
Yes, that's whalt https://github.com/phetsims/molecule-shapes/commit/748a6351e5915728aed1f385bb0a1e34333b52bc does, but I have a large number of constants that assume whether we are using WebGL doesn't change. Additionally, dispose() needs to be rewritten to be able to work with a lost context.

**Comment by jonathanolson** [comment]
Adding and testing with:
```js
phet.joist.sim.screens[0].view.showContextLossDialog()
```

**Comment by jonathanolson** [comment]
Or a more manual:
```js
phet.joist.sim.screens[0].view.threeRenderer.context.getExtension( 'WEBGL_lose_context' ).loseContext();
```

**Comment by jonathanolson** [comment]
Pending on tracking code checking and moving dialog to common code.

**Comment by jonathanolson** [comment]
Tracking code notified properly on context loss.
