### ISSUE TITLE
iOS 7 + Safari Performance

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#102]
Performance is slow with iOS 7 and Safari with most molecules that have octahedral molecular geometry. The performance is very dismal with the larger real molecules (XeF4, BrF5, PCl5, and SF6) coupled with outer lone pairs being shown. Dragging the molecule quickly results in lone pairs lagging behind and detaching from their molecule.

![photo](https://cloud.githubusercontent.com/assets/5863899/6086024/dc5dfc34-adfb-11e4-833f-76ef55c4b205.PNG)

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html
Version: 1.0.0-dev.15
Features missing: fullscreen
User Agent: Mozilla/5.0 (iPad; CPU OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53
Language: en-us
Window: 1024x671
Pixel Ratio: 1/1
WebGL: disabled

**Comment by bryo5363** [comment]
When using Safari 7 w/ WebGL enabled, I also noticed some obscure behavior. When adding single, double or triple bonds in very fast succession the sim will lag and not function properly. To recreate

-open sim
-open model 
-remove all bonds=
-add bonds very rapidly. The sim will lag and not allow the user to access any options on the sim.

**Comment by jonathanolson** [comment]
Doesn't look like we'll be able to do anything for the Canvas performance.

**Comment by ariel-phet** [comment]
Sim is published and iOS7 users are dwindling, closing
