### ISSUE TITLE
IE 11 w/ Canvas slow performance.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/molecule-shapes#105]
Test device: Asus Win 8
Operating System: Win 8
Browser: IE 11.0.9600.17498
Problem description:
Slow performance when moving molecules, adding bonds.

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html?webgl=false
Version: 1.0.0-dev.15
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; ASU2JS; rv:11.0) like Gecko
Language: en-US
Window: 1366x712
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jonathanolson** [comment]
Profiling shows 95% time in the three.js rendering. https://github.com/mrdoob/three.js/releases shows no improvements in Canvas performance.

**Comment by jonathanolson** [comment]
There's nothing I can do to improve this, and it looks acceptable on a few different devices.
