### ISSUE TITLE
Rotating H2O leaves that rotation as default to reset.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/molecule-shapes#106]
Test device: Asus
Operating System: Win 8
Browser: IE 11.0.9600.17498
Problem description:
In the Real Molecules screen any rotation of the default H2O molecule leaves that rotation as the default reset. That is, reset returns H2O to the latest rotation. 
There is a little more weirdness:
After a rotation of H2O reset does not change the state.
If you change to a different molecule after rotating it hitting reset returns you to the H2O molecule (Default state), then hitting reset once more brings you the the rotated H2O molecule. 

Steps to reproduce: 
-Open sim
-Select Real Molecules screen
-Rotate H2O
-Hit Reset

Also
-Rotate H2O
-Select different molecule
-Hit reset
-Hit reset

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: Molecule Shapes
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-dev.15/molecule-shapes_en.html
Version: 1.0.0-dev.15
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; ASU2JS; rv:11.0) like Gecko
Language: en-US
Window: 1366x712
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jonathanolson** [comment]
Reproduced (drag an atom in H2O and reset), should have a fix shortly.
