### ISSUE TITLE
Ensure accessibility is behind a query parameter flag before RC

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#110]

**Comment by pixelzoom** [comment]
Maybe it's implied here, but just in case... This query parameter isn't something that should be specific to molecules-shapes, it should be handled by common code.

**Comment by jonathanolson** [comment]
Yes definitely, this is just a reminder for me that can be tracked.

**Comment by pixelzoom** [comment]
Reopening. 

Presumably this commit was related to this issue: https://github.com/phetsims/joist/commit/34d30e21fd7dade606c051c6a5504ebcd2d407b7

Why is options.accessibility defaulted to `true` in Sim.js?  My understanding was that accessibility is supposed to be turned off for all sims, not just molecule-shapes.

**Comment by pixelzoom** [comment]
You also shouldn't need to do this in sim-specific code, it should be handled in joist:

molecule-shapes-main.js, molecules-shapes-basics-main.js:
> accessibility: !!phet.chipper.getQueryParameter( 'accessibility' ) // TODO: control with query parameter

**Comment by pixelzoom** [comment]
Recommended to replace the previous commit with this in Sim.js:

> 153 accessibility: !!phet.chipper.getQueryParameter( 'accessibility' ),

**Comment by jonathanolson** [comment]
> My understanding was that accessibility is supposed to be turned off for all sims, not just molecule-shapes.

I talked with @samreid, and the plan was explicitly to only disable accessibility by default for Molecule Shapes while the accessibility sprint was going on.

I'm fine with disabling it globally by default, but talk to @samreid first.

**Comment by samreid** [comment]
OK with me to disable globally by default.  Is the reasoning to make sure it is polished before it shows up in our "dev" versions in addition to our published versions?

**Comment by pixelzoom** [comment]
I spoke with @ariel-phet on the phone. He said "off for all sims by default". 

I made the change in Sim.js and removed the query parameter accesses in molecule-shapes and molecule-shapes-basics.  Tested with those sims and a couple of others.  Assigning to @jonathanolson to make sure he's OK with the changes to his sims.

**Comment by pixelzoom** [comment]
@samreid asked:
> Is the reasoning to make sure it is polished before it shows up in our "dev" versions in addition to our published versions?

From 2/17/15 dev meeting notes:
> AP: from KP - hide behind query parameter for now. Definitely want some code review and testing. KP also said that tab ordering should be addressed in a general way (was very squeamish about code ordering being moved around to control tab ordering). We can discuss more on Thursday. We can definitely do some testing with the next RC.
SR: OK, we’ll hide it behind a query parameter for now.

And why would you want to add sim-specific code to disable it? That's code that you need to remember to add, and that will need to be removed at a later date.  That seems like a much greater cost than having to add an 'accessibility' query parameter to test what is an experimental feature.

**Comment by jonathanolson** [comment]
Changes look good, closing.
