### ISSUE TITLE
iFrame is constantly expanding on iPad

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#111]
This was verified on iPad Air 2 (iOS 8.1.3), iPad 2 (iOS 7.0.4), and iPad 3 (iOS 8.1) for both the regular and basic version of molecule shapes, 1.0.0-rc.1

https://drive.google.com/file/d/0B3HJopSo_QqLY1dJX3ZfLWxHdUU/view?usp=sharing

**Comment by jonathanolson** [comment]
Looks like it's happening for any Scenery 0.2 sim.

**Comment by jonathanolson** [comment]
http://stackoverflow.com/questions/16937070/iframe-size-with-css-on-ios

**Comment by jonathanolson** [comment]
More information: http://dev.magnolia-cms.com/blog/2012/05/strategies-for-the-iframe-on-the-ipad-problem/

**Comment by jonathanolson** [comment]
Overridding FittedBlock bounds to an area always within the screen fixes this (padding causes it). Creating Scenery issue for this.

**Comment by jonathanolson** [comment]
Should be fixed in Scenery. Local tests show it working.

**Comment by jonathanolson** [comment]
Fixed in RC.
