### ISSUE TITLE
Sim unusable on IE9

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#113]
Bunch of problems with the controls and navbar, watch the video. The problems get worse the more times the screens are switched. This is on Win 7 and 1.0.0-rc.1 for both the regualr sim and basics.

https://drive.google.com/file/d/0B3HJopSo_QqLbGVvVjJjbjh3Mnc/view?usp=sharing

**Comment by orejolaphet** [comment]
Sim is also unusable on IE 10 Here are some pictures describing the behavior:
![ie10molecules3](https://cloud.githubusercontent.com/assets/5631059/6469577/f3a728cc-c19a-11e4-95d7-26d282cfb093.png)
![ie10molecules2](https://cloud.githubusercontent.com/assets/5631059/6469579/f76285e2-c19a-11e4-85bf-b8092b1013af.png)
![ie10molecules](https://cloud.githubusercontent.com/assets/5631059/6469580/f94620f8-c19a-11e4-91d9-6d3cffd01cbd.png)

**Comment by jonathanolson** [comment]
Tracked down an instance of this, where a tranform is tagged on an svg group where there should be no transform. Code to remove transforms from SVGGroups may be to blame.

**Comment by jonathanolson** [comment]
removeTransform seems to not work?
![scenery-ie9-remove-transform](https://cloud.githubusercontent.com/assets/480878/6474181/f3b32f34-c1bb-11e4-8df0-38c1945e0fd7.png)

**Comment by jonathanolson** [comment]
And confirmation of this from others: http://stackoverflow.com/questions/23814729/ie11-doesnt-remove-transform-attribute-on-svg-text-element

**Comment by jonathanolson** [comment]
Tested with referenced Scenery fix and it's looking correct on IE9. I don't have a VM for IE10, but I anticipate it would be the same issue.

**Comment by jonathanolson** [comment]
Fixed in RC.
