### ISSUE TITLE
PhET button disappears

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#114]
This occurs in 1.0.0-rc.1 on all platforms. It's this problem: https://github.com/phetsims/joist/issues/191.

To reproduce:
1. start the sim
2. select any screen
3. go back to the home screen
4. notice that the horizontal bars in the PhET button are dimmed (their color is set for an inverted navbar)

**Comment by pixelzoom** [comment]
This problem is now fixed in https://github.com/phetsims/joist/issues/191. Not sure how you want to patch this in your release candidate.

**Comment by jonathanolson** [comment]
Thanks. I believe I'll be doing another RC with more recent versions of common libraries, since there are Scenery fixes that need to go into it also.

**Comment by jonathanolson** [comment]
Fixed in RC.
