### ISSUE TITLE
Performance is very sluggish on IE11 Windows 7

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#115]
Test device: Dell Intel Core 2 Duo

Operating System: Windows 7

Browser: IE 11

Problem description: Simulation performance is very sluggish

Steps to Reproduce: Any molecule with 5 or more bonds will cause the simulation to run slow. 

Severity: High

Screenshots:

Troubleshooting information (do not edit):
  
Name: Molecule Shapes

URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.0.0-rc.1/molecule-shapes_en.html

Version: 1.0.0-dev.15

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled

User Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

Language: en-US

Window: 1184x687

Pixel Ratio: 1/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

**Comment by ariel-phet** [comment]
RC2 runs smooth as butter on my IE11. Closing
