### ISSUE TITLE
branch: combo-box-testing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#119]
Being used for debugging https://github.com/phetsims/molecule-shapes-basics/issues/3 (still haven't been able to reproduce). It has extra checks which should help.

**Comment by ariel-phet** [comment]
Since this issue has been addressed, can this be closed @jonathanolson?

**Comment by jonathanolson** [comment]
Branch looks simple enough to rewrite, will delete the branch and close.
