### ISSUE TITLE
molecules-shapes fails to build

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#122]
```
% grunt
...
Writing HTML
Fatal error: Missing string MOLECULE_SHAPES/geometry.empty in fallback locale (en)
% 
```

**Comment by pixelzoom** [comment]
I'm guessing this has something to do with this entry in molecules-shapes-strings_en.json:

```js
  "geometry.empty": {
    "value": ""
  },
```

There are other similar entries. Perhaps the string plugin is not handling the empty string correctly?

**Comment by pixelzoom** [comment]
This made it impossible to test phetsims/chipper#130 (preload generation).  So you'll need to test that after I push related changes.

**Comment by pixelzoom** [comment]
The assertion that's failing is in afterRequirejsBuild.js, line 138:

`assert( fallbackString, 'Missing string ' + stringKey + ' in fallback locale (' + fallbackLocale + ')' )`

**Comment by pixelzoom** [comment]
I fixed this by changing the assertion to allow empty strings:

`assert( fallbackString !== undefined && fallbackString !== null, 'Missing string ' + stringKey + ' in fallback locale (' + fallbackLocale + ')' );`

But I'm wondering:

(1) Was the intent to allow or disallow empty strings?
(2) Why do this sim and least-squares-regression have empty strings in their string files?

**Comment by jonathanolson** [comment]
(1) Was not intending to disallow empty strings,
(2) In this case, allowed flexibility for translators. For English, it makes sense to have the empty string.

**Comment by jonathanolson** [comment]
Additionally, thanks for the fix!
