### ISSUE TITLE
Uneven scaling when window height is bigger than width

### ISSUE THREAD

**Issue by arnabp** [phetsims/molecule-shapes#125]
When using split screen, the scaling from a large window to a small window is linear for the sim, but much stronger for the particle, causing the particle to look very very small for skinny windows.

![screen shot 2015-06-16 at 2 55 56 pm 2](https://cloud.githubusercontent.com/assets/8583364/8194634/06aa16d6-143a-11e5-903d-5ba1e132a756.png)
![screen shot 2015-06-16 at 2 57 18 pm 2](https://cloud.githubusercontent.com/assets/8583364/8194635/06bcbb42-143a-11e5-8451-4eb602244549.png)

**Comment by jonathanolson** [comment]
I don't see any OS X 11 listed in the inventory, which device was used (so I could potentially debug with it)?

**Comment by jonathanolson** [comment]
I'd like to test this in-person to try to see what I can do with the console to debug.

**Comment by arnabp** [comment]
It's on the machine I use now, Erdos, in 1029. I'll be here for the next couple hours if you'd like to try it today.

**Comment by jonathanolson** [comment]
This is actually buggy with the current production version and Safari 7.1.6, and is probably buggy in production for all of Safari.

**Comment by jonathanolson** [comment]
And buggy on Chrome OS X.

**Comment by jonathanolson** [comment]
And buggy with Chrome Windows, and probably every platform.

**Comment by arnabp** [comment]
Whoops, we edited the title at the same time, changing back

**Comment by jonathanolson** [comment]
Fixed on all platforms.
