### ISSUE TITLE
Extremely Long String Test

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molecule-shapes#126]
I tested the extremely long string on the iPad 2. This are just screenshots so you can see what it looks like. Everything worked fine. 
![image 4](https://cloud.githubusercontent.com/assets/12610678/8789783/55f773b2-2f03-11e5-93b8-9c8a38279f28.jpg)
![image 3](https://cloud.githubusercontent.com/assets/12610678/8789789/59a1dcd2-2f03-11e5-9e07-c0034ef570de.jpg)
![image 2](https://cloud.githubusercontent.com/assets/12610678/8789790/5ca18a4a-2f03-11e5-90a0-bdcbf0629d59.jpg)

**Comment by jonathanolson** [comment]
Looks like a long panel title with short content will be buggy. Assigning as bug.

**Comment by jonathanolson** [comment]
Argh, desktop interface on iPhone worked REALLY badly at assigning (I swear I was clicking accurately), since the mobile interface doesn't support it.

Sorry, it should be assigned to me.

**Comment by jonathanolson** [comment]
Should be fixed.

**Comment by elisemorgan** [comment]
@jonathanolson The Long String Test looks much better it's just still a little bit messy on the Real Molecules page. Pretty minor 
Test device: 

Operating System: Windows 8

Browser: Chrome

Problem description: Long String Test

Steps to reproduce:

Severity: Minor 

Screenshots: 
![screenshot 1](https://cloud.githubusercontent.com/assets/12610678/9285980/9bebf93c-42a0-11e5-9717-80bd544573d4.png)


Troubleshooting information (do not edit):
Name: SomeExtrmelyLongStringThatWouldLikelyBreakAnythingDoubleDidNot
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.2/molecule-shapes_en.html?stringTest=SomeExtrmelyLongStringThatWouldLikelyBreakAnythingDoubleDidNot
Version: 1.1.0-rc.2 2015-08-13 21:13:26 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
Language: en-US
Window: 1920x919
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"5be7fe04","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"aa39bc48","branch":"master"},"chipper":{"sha":"51c45026","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"e9f47dd3","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecule-shapes":{"sha":"43fc3142","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"be4fc88f","branch":"master"},"scenery-phet":{"sha":"78082cb3","branch":"master"},"sherpa":{"sha":"1759eade","branch":"master"},"sun":{"sha":"1320a557","branch":"master"}}
