### ISSUE TITLE
Minor Dragging Glitch in iFrame 

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/molecule-shapes#127]
Test device: Acer Chromebook

Operating System: Chrome OS

Browser: Chrome 43.0.2357.134

Problem description: After clicking and dragging the molecule, the molecule would continue to move with the mouse after no longer being clicked. This is not very problematic because I just had to click the screen again and the molecule was released. The issue also occurred when an external mouse was used.

Steps to reproduce: Open iFrame. Click and drag molecule around. Release molecule and see if it continues moving. It may take a couple of attempts at first.

Severity: Minor

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Molecule Shapes‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.1/molecule-shapes_en.html
Version: 1.1.0-rc.1 2015-07-20 18:55:19 UTC
Features missing: touch
User Agent: Mozilla/5.0 (X11; CrOS x86_64 6946.86.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
Language: en-US
Window: 1366x657
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 96)
Max viewport: 8192x8192
OES_texture_float: false
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"42896196","branch":"phet"},"chipper":{"sha":"d5bea1ca","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a5de6c77","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecule-shapes":{"sha":"8a2784f4","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"fdc6e97a","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"}}

**Comment by jonathanolson** [comment]
Confirmed with Chadwick, and I can also reproduce on OS X Chrome.

Looks initially like mouse events aren't being sent while the mouse is outside of the iframe (so the mouse release isn't picked up), and it still thinks it's being dragged. Also doesn't pick up movement.

I'll see if I can figure out any flag settings or Chrome options so that it will work as expected. Should be an issue across all sims.

**Comment by jonathanolson** [comment]
Chromium bug that causes the current behavior: https://code.google.com/p/chromium/issues/detail?id=269917

Not too much we can do at this point from our end. @ariel-phet, should an issue be created in joist/scenery and left open to note this as an all-sims-in-iframe-in-Chrome issue?

**Comment by ariel-phet** [comment]
@jonathanolson yes that seems like an appropriate step. Agreed that not much we can do about this at the moment. Feel free to reference new issue and close this one.
