### ISSUE TITLE
Aliasing present on FF 38.0.5

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#129]
There is a clear difference in sim appearance from Chrome to FF

Chrome 43 on OSX 10.10.3
![screen shot 2015-07-22 at 9 36 13 am](https://cloud.githubusercontent.com/assets/7717368/8829671/1f280790-3055-11e5-84fc-7e0bb6b2c3e2.png)

FF 38.0.5 on OSX 10.10.3
![screen shot 2015-07-22 at 9 36 23 am](https://cloud.githubusercontent.com/assets/7717368/8829682/2bdfc27a-3055-11e5-9e3d-17b5ff2aabfa.png)

**Comment by ariel-phet** [comment]
@bryo5363 can you try updating to the latest FF (I believe it is at 39)

**Comment by bryo5363** [comment]
This is still present on FF 39. There is no aliasing with the text but the resolution and smoothing of the actual molecules still looks the same as 38.0.5

**Comment by ariel-phet** [comment]
@bryo5363 - thanks for the update

**Comment by ariel-phet** [comment]
@jonathanolson - I assume there is nothing to be done about this issue...it is basically a question of the FF webgl rendering engine...is that correct?

**Comment by jonathanolson** [comment]
There might be something to be done. It may be the case where it won't easily be solvable easily.

If it's a big sticking point, it would be possible to ship the partially-transparent images for the control panel in the sim itself (for all color-schemes), instead of having them be generated, if I can't find a better solution.

**Comment by ariel-phet** [comment]
@jonathanolson - not a big sticking point, we of course love our sims looking as crisp as possible, but this level of aliasing is acceptable. So if there is an reasonably easy improvement, it is worth considering, but I do not think we need to go to the lengths of shipping partially transparent images for the control panel.

**Comment by jonathanolson** [comment]
Added on-the-fly mipmapping to Firefox, fixes the aliasing issue.
