### ISSUE TITLE
Simulation crashes on Safari 7

### ISSUE THREAD

**Issue by bryo5363** [phetsims/molecule-shapes#131]
Test device: MacBook Pro

Operating System: OSX 10.9.4

Browser: 7.0.5 (9537.77.4)

Problem description: The simulation crashes when going from full screen to external link

Steps to reproduce:
1) open sim
2) go full screen 
3) click report a problem or phet website
4) when going back to the simulation tab on the browser, the simulation will not run
Severity:

Screenshots:
![screen shot 2015-07-22 at 12 10 50 pm](https://cloud.githubusercontent.com/assets/7717368/8833182/ba1239c8-306a-11e5-8d16-7a2b8ba6a9c9.png)

Troubleshooting information (do not edit):
Name: ‪Molecule Shapes‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.0-rc.1/molecule-shapes_en.html
Version: 1.1.0-rc.1 2015-07-20 18:55:19 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4
Language: en-us
Window: 1280x631
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (2.1 INTEL-8.24.15)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"858e65ac","branch":"master"},"axon":{"sha":"579f8c66","branch":"master"},"babel":{"sha":"2431e711","branch":"master"},"brand":{"sha":"42896196","branch":"phet"},"chipper":{"sha":"d5bea1ca","branch":"master"},"dot":{"sha":"e34c6b2c","branch":"master"},"joist":{"sha":"a5de6c77","branch":"master"},"kite":{"sha":"24978146","branch":"master"},"molecule-shapes":{"sha":"8a2784f4","branch":"1.1"},"nitroglycerin":{"sha":"c6f79ce4","branch":"master"},"phet-core":{"sha":"8e31808c","branch":"master"},"phetcommon":{"sha":"89a44d2c","branch":"master"},"scenery":{"sha":"24a4d9ab","branch":"master"},"scenery-phet":{"sha":"f3f30545","branch":"master"},"sherpa":{"sha":"fdc6e97a","branch":"master"},"sun":{"sha":"dc08e5f3","branch":"master"}}

**Comment by bryo5363** [comment]
Note that WebGL does NOT need to be enabled for this issue to occur

**Comment by jonathanolson** [comment]
Confirmed using Dirac. No console errors or anything else, and it's fixed in Safari 8.x+.

I'm not sure there's a fix besides disabling full-screen for Safari 7.x (and I can't pin down any workarounds online). @ariel-phet, preferences between disabling full-screen for 7.x, or just marking as will-not-fix?

**Comment by ariel-phet** [comment]
Disable full-screen for 7.x (I assume that this will be a general disabling, not just for this sim).

**Comment by jonathanolson** [comment]
> I assume that this will be a general disabling, not just for this sim

Correct, will do.

**Comment by jonathanolson** [comment]
Tested above commit, verified that full-screen is disabled in Safari 7. Closing.
