### ISSUE TITLE
"Real" button lost and text box overlap with long test

### ISSUE THREAD

**Issue by BryceAG** [phetsims/molecule-shapes#137]
Test device:
Dirac, Bates

Operating System:
OS X 10.11.2, Windows 7

Browser:
Chrome, Safari, Firefox, Internet Explorer

Problem description:
Using the long test and in the real molecules section the button for the "real" molecule shape is offscreen to the left. It is still clickable by clicking the text. The window can be stretched so that it is onscreen, but it is off for fullscreen. The text for "model" also overlaps the molecule selection box to the right.

Steps to reproduce:
Use the long test and go to the real molecules section.

Severity:

Screenshots:
![screen shot 2016-01-15 at 11 39 11 am](https://cloud.githubusercontent.com/assets/15327201/12361650/ae99e594-bb7c-11e5-9862-b431b25caeb4.png)

Troubleshooting information (do not edit):
Name: 12345678901234567890123456789012345678901234567890
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.2-rc.1/molecule-shapes_en.html?stringTest=long
Version: 1.1.2-rc.1 2016-01-14 22:08:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Language: en-US
Window: 1279x637
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"6351434f","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"72a39f97","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"joist":{"sha":"fa1196f6","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"molecule-shapes":{"sha":"74bdad4d","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"HEAD"},"phet-core":{"sha":"f78b5cfe","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6bed84d9","branch":"HEAD"},"sherpa":{"sha":"ae737ccb","branch":"HEAD"},"sun":{"sha":"982a49b8","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by phet-steele** [comment]
Related to phetsims/tasks/issues/477

**Comment by BryceAG** [comment]
Also related, in the model section, the "Remove All" button is (barely) cut off on the right in long test. This is also seen in Molecule shapes basics. Related to phetsims/tasks#478

**Comment by ariel-phet** [comment]
@jonathanolson just as a reminder note, we want to make sure ?stringTest=double passes, but problems encountered with ?stringTest=long do not necessarily need to be addressed
