### ISSUE TITLE
i18n Name box dynamically resizes

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#138]
Potential i18n issue:

If it so happens that during a translation, the "Trigonal Bipyramidal" string becomes longer, an incredibly distracting box resize occurs when adding or removing objects. Easily seen with stringTest=double and in the below gif. Watch that the bottom left "Name" box gets larger when any geometry becomes trigonal bupyramidal. This happens regardless of whether the show/hide check boxes are checked or not. Happens in the Basics version as well. Tested on 1.1.2-rc.1 and 1.1.0-rc.2 (Basics) with Win 8.1 & 10, personal device and Galileo(?). FF & Edge.

![molsha](https://cloud.githubusercontent.com/assets/5863899/12363035/afd5b9e0-bb83-11e5-841e-b0761e3f1aa4.gif)

Troubleshooting information:
Name: ‪Molecule Shapes‬:‪Molecule Shapes‬
URL: http://www.colorado.edu/physics/phet/dev/html/molecule-shapes/1.1.2-rc.1/molecule-shapes_en.html?stringTest=double
Version: 1.1.2-rc.1 2016-01-14 22:08:44 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Language: en-US
Window: 1366x633
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 28 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"6351434f","branch":"master"},"brand":{"sha":"c9282935","branch":"HEAD"},"chipper":{"sha":"72a39f97","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"joist":{"sha":"fa1196f6","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"molecule-shapes":{"sha":"74bdad4d","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"HEAD"},"phet-core":{"sha":"f78b5cfe","branch":"HEAD"},"phetcommon":{"sha":"d712ace0","branch":"HEAD"},"scenery":{"sha":"ace9a1cc","branch":"HEAD"},"scenery-phet":{"sha":"6bed84d9","branch":"HEAD"},"sherpa":{"sha":"ae737ccb","branch":"HEAD"},"sun":{"sha":"982a49b8","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@phet-steele going forward for RC test task issues please reference the original task when creating the issue (I will be spreading the word to all testers). For instance just comment

Related to https://github.com/phetsims/tasks/issues/477

**Comment by phet-steele** [comment]
@ariel-phet oh right! Forgot that was a new thing.

**Comment by ariel-phet** [comment]
@phet-steele could you maybe also put this in the "ticket instructions" doc?

https://docs.google.com/document/d/1snxCn_qN5lrlNc-0ZU-3Wp8dG3eoJx8mNzT5jfL4nuQ/edit#heading=h.j1r8g764lruu

**Comment by phet-steele** [comment]
@ariel-phet what's the reason for not doing this for dev testing, if there is a reason?

**Comment by ariel-phet** [comment]
@phet-steele doesn't hurt for dev testing, but RC testing is a bit more "codified"

**Comment by jonathanolson** [comment]
Somehow this is working on my local machine, but still broken on the RC and phettest.colorado.edu?

**Comment by ariel-phet** [comment]
fix confirmed, closing
