### ISSUE TITLE
"Open" control panel titles look bad when in front of molecule

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#139]
@phet-steele noticed a graphical quirk when strings are longer and outer lone pairs are enabled on big molecules.

This is most noticeable when stringTest=double or longer, but can be triggered for a fraction of a second in the English translation (by quickly moving XeF4 with lone pairs enabled):

![screen shot 2016-01-28 at 2 47 57 pm](https://cloud.githubusercontent.com/assets/480878/12659921/6b86e4bc-c5ce-11e5-8be3-877e38c9f1bd.png)

@ariel-phet, should this behavior be changed, and if so, what should it look like?

**Comment by jonathanolson** [comment]
Noticed in testing for https://github.com/phetsims/tasks/issues/491

**Comment by ariel-phet** [comment]
@jonathanolson I agree that is a bit distasteful (and good observation @phet-steele!)

In this particular case, I think this situation will be rare, and although a bit aesthetically displeasing, I think it is not currently worth addressing considering the rarity.

Marking "wonfix" and closing
