### ISSUE TITLE
Replace getQueryParameter with QueryStringMachine

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#142]
Factored out of phetsims/query-string-machine#15

**Comment by pixelzoom** [comment]
This sim doesn't have a *QueryParameters file, so I'm not going to do the conversion.

**Comment by pixelzoom** [comment]
This was making it difficult to proceed with phetsims/query-string-machine#15, so I did the conversion. @jonathanolson please review.

**Comment by jonathanolson** [comment]
Looks good.
