### ISSUE TITLE
User reported issue: Chrome behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecule-shapes#144]
Test device: Mac (2.7 GHz Core i5, 4 GB 1333 MHz DDR3 RAM)

Operating System: OS X 10.9.5

Browser: Google Chrome, the latest version (it works perfectly in Firefox and Safari)

Problem description: The molecule doesn't appear on the black background, only a white screen is there

Steps to reproduce: Simply open the simulation in the latest version of Chrome, and select either "model" or "real molecules".

Severity: Makes the simulation unusable in Chrome

Screenshots:
![screen shot 2016-12-21 at 4 29 30 pm](https://cloud.githubusercontent.com/assets/5090275/21408695/a01153a8-c793-11e6-99e8-019c124ba234.png)

Troubleshooting information (do not edit):
Name: ‪Molecule Shapes‬
URL: https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html
Version: 1.1.8 2016-12-06 23:58:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36
Language: en-US
Window: 1351x1212
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 768
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"d4909677","branch":"HEAD"},"axon":{"sha":"5a39ec57","branch":"HEAD"},"babel":{"sha":"4757b7e5","branch":"master"},"brand":{"sha":"11458b27","branch":"HEAD"},"chipper":{"sha":"72a39f97","branch":"HEAD"},"dot":{"sha":"7a28b1a9","branch":"HEAD"},"joist":{"sha":"43cc9a8b","branch":"HEAD"},"kite":{"sha":"4a947119","branch":"HEAD"},"molecule-shapes":{"sha":"43cfc58d","branch":"HEAD"},"nitroglycerin":{"sha":"ef8c55a2","branch":"HEAD"},"phet-core":{"sha":"f78b5cfe","branch":"HEAD"},"phetcommon":{"sha":"01ee2aff","branch":"HEAD"},"scenery":{"sha":"a424086e","branch":"HEAD"},"scenery-phet":{"sha":"6bed84d9","branch":"HEAD"},"sherpa":{"sha":"ae737ccb","branch":"HEAD"},"sun":{"sha":"982a49b8","branch":"HEAD"},"tandem":{"sha":"873e0387","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@oliver-phet you were able to reproduce?

**Comment by oliver-phet** [comment]
No. I didn't try our 10.9 machine, but couldn't on mine.

**Comment by ariel-phet** [comment]
@oliver-phet lets first see if we can reproduce on our 10.9 machine before having JO take a look. If you cannot reproduce on 10.9, lets see if the user can let us know their GPU. Also could you have the user run on chrome with `?webgl=false` (I have a sneaking suspicion this might be a webgl/blacklisted GPU issue)

**Comment by ariel-phet** [comment]
@oliver-phet actually regardless it would be good to ask the user to run with `?webgl=false` as that might narrow the issue

**Comment by oliver-phet** [comment]
Asked for another update from the user. If I don't hear back, I'll close this issue for now.

**Comment by jonathanolson** [comment]
I'll want to check whether this is related to https://github.com/phetsims/molecule-shapes/issues/145

**Comment by oliver-phet** [comment]
I just heard back from the user: 

> I'm back from Christmas break now, thanks for pursuing this problem!  The link you send to run the simulation in Canvas works perfectly, thanks.

**Comment by oliver-phet** [comment]
I just got around to testing on one of our 10.9.5 machines and this behavior wasn't reproducible.

**Comment by oliver-phet** [comment]
Assigning this back to AP.

**Comment by ariel-phet** [comment]
Seems like one of the GPU issues. So not worth pursuing further. 

@oliver-phet I would say for any future issues like this, try the ?webgl=false method with users as a first step.
