### ISSUE TITLE
phet.joist.sim.version is 'joist internal'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#147]
MoleculeShapesScreenView contains this bit of code:

```js
if ( document.domain === 'phet.colorado.edu' ) {
  window._gaq && window._gaq.push( [ '_trackEvent', 'WebGL Context Loss', 'molecule-shapes ' + phet.joist.sim.version, document.URL ] );
}
```

`phet.joist.sim.version` is annotated as `@public (joist-internal)`, so Molecule Shapes should not be using it. And it's causing me problems over in phetsims/joist#406, where I am investigating making `sim.version` go away.

**Comment by jonathanolson** [comment]
What is the proposed way of getting the sim version?

**Comment by pixelzoom** [comment]
How about using SimVersion? https://github.com/phetsims/joist/issues/406#issuecomment-284888193

**Comment by jonathanolson** [comment]
The proposed sim.simVersion (a {SimVersion}) is joist-internal? Or is there another way?

At the time of the commit that added this (https://github.com/phetsims/molecule-shapes/commit/b3c9374bf7c84085a08f68e084e53ca741305f5c), `sim.version` had no visibility annotation (https://github.com/phetsims/joist/blob/34d30e21fd7dade606c051c6a5504ebcd2d407b7/js/Sim.js), and presumably it was public?

**Comment by jonathanolson** [comment]
I'll be happy to change the molecule-shapes/neuron usages when there's a public way to get the version string (I didn't see one, let me know if one exists now).

**Comment by pixelzoom** [comment]
> At the time of the commit that added this (b3c9374), sim.version had no visibility annotation 

`@public (joist internal)` was added by @samreid in https://github.com/phetsims/joist/blob/929223ee36707f75badd5845d142ffcafded5f11/js/Sim.js

**Comment by pixelzoom** [comment]
@jonathanolson What was your vision for SimVersion? Looks like you added it for UpdateCheck (the only use).

**Comment by jonathanolson** [comment]
> @jonathanolson What was your vision for SimVersion? Looks like you added it for UpdateCheck (the only use).

A common place for parsing/comparing or analyzing versions, such as the question "is this a production version" that we're encountering now, so that logic wouldn't be duplicated in multiple places. Doesn't really solve that at the moment, as we can't use it in Node.js code.

Pulling it out so perennial could use it (for build-server and maintenance releases) complicates things massively if it ever would change in implementation, and is somewhat the same with Yotta, so I've kept it require.js-only.

**Comment by pixelzoom** [comment]
3/9/17 dev meeting:
Molecule Shape and Neuron use this same bit of "context loss listener" code.  Factor that out (and address the version identifier issue) in https://github.com/phetsims/phetcommon/issues/38.
Closing.
