### ISSUE TITLE
Non-WebGL screenshot is reversed

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#149]
So this is a bit weird, but when a screenshot is taken when WebGL is disabled, it seems to be flipped:

Actual screenshot (from OS):
![molecule-shapes-manual-screenshot-1](https://user-images.githubusercontent.com/480878/47407041-76f7be00-d716-11e8-88de-40234f723714.PNG)

From the PhET menu:
![molecule-shapes-auto-screenshot-1](https://user-images.githubusercontent.com/480878/47407045-7eb76280-d716-11e8-8dde-8c2f1b5ca0fc.png)

Looks like a vertical flip.

**Comment by jonathanolson** [comment]
Should be fixed above. @ariel-phet I assume this is not significant enough for a maintenance release?

**Comment by ariel-phet** [comment]
@jonathanolson agreed not significant enough for a maintenance release (especially since people should mostly be on browsers that support WebGL these days)

**Comment by KatieWoe** [comment]
It now seems to be completely missing from the screenshot when webgl is off.  I think between the two.  Reversed would be preferred.  Taken with webgl=false query parameter.
Actual view taken with Win 10 tool:
![actual](https://user-images.githubusercontent.com/41024075/52869945-067d0e80-3104-11e9-9d50-c101e772c39b.jpg)
PhET menu screenshot:
![molecule shapes_ basics screenshot 1](https://user-images.githubusercontent.com/41024075/52870058-37f5da00-3104-11e9-81d0-6d40ca253de9.png)

**Comment by KatieWoe** [comment]
Actually, looking at some more, it seems to move elsewhere:
![molecule shapes screenshot](https://user-images.githubusercontent.com/41024075/52870308-c9654c00-3104-11e9-83a9-061b35486a82.png)

**Comment by KatieWoe** [comment]
Update: this seems to happen on most platforms I've checked, but I've found at least one so far (Win 7 chrome) that doesn't.

**Comment by KatieWoe** [comment]
Odd webgl=false behavior I noticed in some cases while looking at this.  In https://github.com/phetsims/QA/issues/280 (basics) there seems to be a black box around the atoms that can be added in the model screen.
![molecule shapes_ basics screenshot-1](https://user-images.githubusercontent.com/41024075/53188593-f7460700-35c2-11e9-9a72-c023313bc829.png)

**Comment by jonathanolson** [comment]
@KatieWoe does the Win 7 Chrome by chance have a high-definition screen?

**Comment by KatieWoe** [comment]
I do not believe it does @jonathanolson

**Comment by jonathanolson** [comment]
I believe the "missing/repositioned molecule during non-webgl screenshot" should be resolved in master (and branches), can you verify?

Also, what platform has the black boxes on the basics screenshot? I can't reproduce that locally.

**Comment by KatieWoe** [comment]
There were a few.  Win 7 chrome was the first I noticed.  I think some of the Macs had it too, but it seemed a bit random.

**Comment by KatieWoe** [comment]
Screenshot issue looks solved on Win 10 chrome and edge.  Couldn't check Win 10 firefox due to separate issue.

**Comment by jonathanolson** [comment]
Black box issue being Firefox-specific looks like the potential result of custom code for https://github.com/phetsims/molecule-shapes/issues/129

**Comment by jonathanolson** [comment]
It looks like THREE.js' canvas renderer on Firefox is not respecting the background transparency.

It still allowed me to set a background color properly (non-transparent), so I'm setting it to the background color of the sim (set to update) instead as a workaround.

@KatieWoe I believe these should now be fixed in master (and branches). Can you verify the black boxes, or let me know if there is a blocking issue preventing testing?

**Comment by KatieWoe** [comment]
https://github.com/phetsims/molecule-shapes/issues/156 prevents testing on that particular platform.

**Comment by KatieWoe** [comment]
https://github.com/phetsims/molecule-shapes/issues/161#issuecomment-466456636 makes testing those platforms difficult as well.  I'll find at least two platforms that show the issue on the rc and verify they are fixed.

**Comment by KatieWoe** [comment]
Checked at least two platforms.  Both seem fixed. @jonathanolson

**Comment by KatieWoe** [comment]
Since this is published I think it can be closed.  Your call @jonathanolson
