### ISSUE TITLE
Republish from master: Deliver ePub version

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-shapes#150]
A client has requested the ePub compatible files for this simulations. Deadline for delivery is in March, but perhaps we can fit it in soonish if there are no real barriers to republishing from master and JO has a bit of time to review.

This would have the benefit of also capturing Legends of Learning support. Let's touch base on this at status tomorrow, and look at current QA load to see if now is a good time or not. Should do this when QA load is light.

**Comment by jonathanolson** [comment]
Sounds good to me. Also looks like Area Model 1.1 should be ready to branch (those could be done at the same time).

**Comment by samreid** [comment]
Maybe Graphing Quadratics can get the same SHAs?  And Wave Interference is hopefully not far off.

**Comment by jonathanolson** [comment]
> Does this just mean that we could put 8 sims all on the same version of "Master"?

It's possible, as long as it's ok to wait until they are all ready (and one developer would make all the branches at the same time).

**Comment by kathy-phet** [comment]
Their is an ePub version up on the website. Looks like this was published back in 2019. Closing.
