### ISSUE TITLE
Low graphics warning

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/molecule-shapes#152]
**Operating System**

Windows 10

**Browser**

Chrome

**Problem Description**

"Running with low graphics quality" warning on the home screen. Seen on multiple browsers on a Win10 machine and a macOS machine.

NB, only seen on MSB.

**Visual**

![screenshot 17](https://user-images.githubusercontent.com/31285590/52824350-61b3f000-3075-11e9-96f5-e2f5db8d58dc.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
Name: ‪Molecule Shapes: Basics‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/molecule-shapes-basics_en_phet.html
Version: 1.2.0-rc.1 2019-02-01 18:53:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
Language: en-US
Window: 1280x610
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
Linking to the rc: https://github.com/phetsims/QA/issues/280

**Comment by KatieWoe** [comment]
Also note that it does not actually appear that webgl is off.

**Comment by phet-steele** [comment]
This is NOT occurring in the published version (1.1.16).

**Comment by jonathanolson** [comment]
Ahh, looks like https://github.com/phetsims/molecule-shapes/commit/8d550e8cd016bf3d04e798f0e1d9985620c8bdaf#diff-54482e48a60d8bed87793f4c2c30eb31 only hit the non-basics version in the refactoring!

**Comment by jonathanolson** [comment]
Should be patched in master and on the RC. Can you verify in master?

**Comment by KatieWoe** [comment]
Confirmed in master

**Comment by KatieWoe** [comment]
Looks good in rc.2
