### ISSUE TITLE
Red X appears on bond atoms not present upon load

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#154]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
Chrome
**Problem description:**
For https://github.com/phetsims/QA/issues/279 and https://github.com/phetsims/QA/issues/280
Upon first load and entering the Model screen, the red "get rid of" x's are present on all possible options, even though they should only be on the single bond.  Clicking on these red x's that aren't meant to be there does nothing.  Many actions, such as adding or taking away a bond/lone pair or hitting the orange reset all button removes this issue and it will only reappear upon a fresh reload.
**Steps to reproduce:**
1. Do a fresh load of the sim
2. Go to the model screen
3. Observe bond options.

**Screenshots:**
![redxonall](https://user-images.githubusercontent.com/41024075/52872204-25ca6a80-3109-11e9-831a-30104d5019f6.jpg)

Troubleshooting information (do not edit):

<details>

Name: ‪Molecule Shapes: Basics‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/molecule-shapes-basics_en_phet.html
Version: 1.2.0-rc.1 2019-02-01 18:53:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36
Language: en-US
Window: 1536x731
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by phet-steele** [comment]
This is NOT occurring in the published version (1.1.16).

**Comment by jonathanolson** [comment]
Identified a bug in the refactor of https://github.com/phetsims/molecule-shapes/commit/8d550e8cd016bf3d04e798f0e1d9985620c8bdaf#diff-c34bf7980f76ded9f8ba659f8ec22626, will have it fixed soon.

**Comment by jonathanolson** [comment]
Patched on master and RC branches. Can you verify in master?

**Comment by KatieWoe** [comment]
Confirmed on master

**Comment by KatieWoe** [comment]
Looks good on rc.2
