### ISSUE TITLE
Projector Mode max width short

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#155]
For https://github.com/phetsims/QA/issues/279
When stringTest=long click on the options from the PhET menu and observe that the bottom line is shorter than the one above it.
![optionmaxwidth](https://user-images.githubusercontent.com/41024075/52879060-85317600-311b-11e9-94ba-feba271aa273.jpg)

**Comment by jonathanolson** [comment]
Should be patched in master and the RC branches, can you verify master?

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Looks good in rc.2
