### ISSUE TITLE
Win 10 Firefox Model Screen blank

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#156]
**Test device:**
Dell and Hanson
**Operating System:**
Win 10 (Happens on both Win 10 test devices)
**Browser:**
Firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/279 and https://github.com/phetsims/QA/issues/280
Only seen so far on Win 10 firefox.  Not on Win 7 or Mac.
The model screen is blank except for the PhET button and the molecule.  When the PhET button is clicked the nav bar appears.  You can seem to click on things where the toolbar would be, but any additions are invisible.  You can turn on projector mode, but the check mark that indicates this doesn't appear, or won't turn off if already on.  webgl=false does not change this. 
**Steps to reproduce:**
1. Go to the model screen of either sim on Win 10 firefox.
2. To see the projector mode part of the issue, open the phet menu and select the projector mode option.

**Screenshots:**
![firefoxgone](https://user-images.githubusercontent.com/41024075/52881707-8e721100-3122-11e9-8852-554ebb2da836.jpg)
![firefoxmessedup](https://user-images.githubusercontent.com/41024075/52881708-8e721100-3122-11e9-8a17-8052325b1f82.gif)

Troubleshooting information (do not edit):

<details>

Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_en_phet.html
Version: 1.2.0-rc.1 2019-02-01 18:51:14 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0
Language: en-US
Window: 1536x760
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Attempting to take a screenshot in this condition freezes the screen.

**Comment by KatieWoe** [comment]
Parts have reappeared when using showPointerAreas after switching between the screen.  Not all parts, and everything flickers.

**Comment by KatieWoe** [comment]
The image on the nav bar seems to always highlight the real molecules page.

**Comment by phet-steele** [comment]
Associated error:
```
TypeError: canvas is undefined[Learn More] molecule-shapes_all_phet_debug.html:155597:9
    updateURL https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:155597
    updateSVGSelf https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:155546
    updateSVG https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:118935
    update https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:118927
    update https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:131861
    update https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:135338
    update https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:131160
    update https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:135338
    updateDisplay https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:143631
    listener https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:180982
    emit https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:85159
    stepSimulation https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:181669
    stepOneFrame https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:181650
    runAnimationLoop https://phet-dev.colorado.edu/html/molecule-shapes/1.2.0-rc.1/phet/molecule-shapes_all_phet_debug.html:181633
    runAnimationLoop self-hosted:974
```

**Comment by phet-steele** [comment]
This is NOT occurring in the published version (1.1.16).

**Comment by jonathanolson** [comment]
Turns out this was fixed in https://github.com/phetsims/scenery/commit/5fe8d2b5e61f14a2550d36617fccfebcce93365d.

**Comment by KatieWoe** [comment]
Seems fixed in rc.2
