### ISSUE TITLE
Molecules can change other molecule's orientation

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#157]
For https://github.com/phetsims/QA/issues/280 and https://github.com/phetsims/QA/issues/279
Found on the real molecules screen when using the dropdown box to select different molecules.  When you move a molecule by clicking on it and dragging it, then switch to a different molecule, that molecule is unaffected and returning to  the original resets it to its default position.  If you click in another area of the screen and drag it still moves the molecule.  However, this changes the orientation of the other molecules as well.  Returning to the original shows that the molecule now has a new default position it will return to.
This occurs in the published version and is very minor.  From @jonathanolson on slack:
> I don't have a problem with a functional change that either makes them independent, or resets the transformation for each real molecule.

**Comment by arouinfar** [comment]
Nice catch @KatieWoe. This is definitely a bit strange.

Steps to reproduce:
1. On startup, change water's orientation by clicking on the molecule itself.
2. Switch to a different molecule.
3. Switch back to water. The orientation has reverted to the startup orientation:

![water](https://user-images.githubusercontent.com/8419308/52981298-10b93a00-339c-11e9-8608-e401f57ee072.gif)

4. Change water's orientation by clicking an empty part of the play area and dragging it.
5. Switch to another molecule. Its orientation now matches water.
6. Switch back to water. Its orientation remains as you left it in step (4).

![water2](https://user-images.githubusercontent.com/8419308/52981343-773e5800-339c-11e9-9748-8ffdf2ea2717.gif)

Steps 1-3 don't seem so odd to me, but steps 4-6 are super weird. Not only have I changed water's orientation -- I've changed everything's orientation and have essentially overwritten the startup orientation.

@jonathanolson I think it would make the most sense to follow the behavior in steps 1-3, regardless of whether the molecule or empty play area was clicked and dragged.

**Comment by jonathanolson** [comment]
Implemented and patching in the release branches. @KatieWoe can you verify master?

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by KatieWoe** [comment]
Seems fixed in rc.2
