### ISSUE TITLE
Color of Br is incorrect

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#159]
Discovered in #153, and should be addressed before the next release, so tagging https://github.com/phetsims/QA/issues/280 too.

According to https://github.com/phetsims/nitroglycerin/blob/master/js/Element.js, the color of bromine (Br) should be `rgb(190,30,20)` and boron (B) should be `rgb(255,170,119)`.

Currently, it appears Br and B are both `rgb(255,170,119)`.

BrF5:
![image](https://user-images.githubusercontent.com/8419308/52978537-ffb5fc00-338e-11e9-853a-1c1c8526d8dc.png)

BF3:
![image](https://user-images.githubusercontent.com/8419308/52978547-08a6cd80-338f-11e9-9f87-12534c39f3d4.png)

**Comment by jonathanolson** [comment]
Should be patched in master and the release branches. Can you verify?

**Comment by arouinfar** [comment]
@jonathanolson I pulled all, but the color of Br and B still appear to be the same in master.  Not sure what's going on.

**Comment by jonathanolson** [comment]
I hadn't pushed somehow, sorry! Fixed, and tested on another computer to ensure. Can you verify?

**Comment by arouinfar** [comment]
Looks good in master @jonathanolson!

**Comment by KatieWoe** [comment]
This seems to be correct in rc.2
