### ISSUE TITLE
Sim runs without webgl on Mac 10.11 chrome

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#162]
**Device**
Dirac
**OS**
10.11.6 and 10.12.6 (and 10.10 but this browser is not supported there)
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/279 and https://github.com/phetsims/QA/issues/280
WebGL seems to be off for the latest google chrome on Mac 10.11.6.  webgl=true does not seem to do anything.  Webgl does not seem to be off for the other browsers on 10.11, and has not seemed to be off on chrome on 10.14 or 10.13.  Is a problem in published version

**Comment by jonathanolson** [comment]
What does the Report a Problem / troubleshooting info for the sim say about WebGL status?

**Comment by KatieWoe** [comment]
```
Troubleshooting information (do not edit):
Name: ‪Molecule Shapes: Basics‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.1/phet/molecule-shapes-basics_en_phet.html
Version: 1.2.0-rc.1 2019-02-01 18:53:54 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36
Language: en-US
Window: 1180x698
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 32 varying: 32 uniform: 256
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
```

**Comment by jonathanolson** [comment]
Interesting. Just tested, and it looks like WebGL is potentially "technically" supported on Dirac, however because we provide the option failIfMajorPerformanceCaveat, the sim won't use it. I manually tested without that, and WebGL is SLOW if we use it (the canvas fallback is much nicer on Dirac).

@KatieWoe is there a good place to note that Dirac (or probably other devices like it) will not use WebGL due to the performance drawback?

**Comment by KatieWoe** [comment]
I'll make a note to add it to the QA book.  Why was it only on chrome?

**Comment by jonathanolson** [comment]
I didn't check the other browsers, but if it's only Chrome doing that then it's probably due to Chrome blacklisting the GPU or OS.

**Comment by KatieWoe** [comment]
Firefox is doing some other weird graphical things.  https://github.com/phetsims/molecule-shapes/issues/161

**Comment by jonathanolson** [comment]
It seems the Firefox item is either unrelated (if it's a security issue that caused the blacklisting), or potentially due to general bugginess. Unassigning.

**Comment by jonathanolson** [comment]
Since I believe we shouldn't change behavior here, I'm marking as will-not-fix.

**Comment by arouinfar** [comment]
Since this is tagged as wontfix, I'll close.
