### ISSUE TITLE
Screenshot shows bonded atom selections as lone pairs

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#164]
For https://github.com/phetsims/QA/issues/301 and https://github.com/phetsims/QA/issues/302
Found while testing https://github.com/phetsims/molecule-shapes/issues/156.  Seen so far on Win 10 firefox.
When taking a screenshot from the phet menu the items in the tool box that represent single, double, and triple bonded atoms all seem to look like the lone pair selection.
![Molecule Shapes screenshot(1)](https://user-images.githubusercontent.com/41024075/55169506-84d4c380-513a-11e9-8512-8a979150a108.png)

**Comment by kathy-phet** [comment]
Confirmed this too. Perhaps related to firefox smaller bond image issue. This should be fixed.

**Comment by KatieWoe** [comment]
Looks good in the two rcs
