### ISSUE TITLE
Small bonded atoms

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#166]
**Test device:**
Dell
**Operating System:**
Win 10
**Browser:**
firefox
**Problem description:**
For https://github.com/phetsims/QA/issues/301 and https://github.com/phetsims/QA/issues/302
 The bonded atoms in the toolbox on the model screen seem smaller than normal.
**Steps to reproduce:**
1. Open the sim in Win 10 firefox.
2. Go to model screen
3. Compare to chrome

**Screenshots:**
Normal
![sizeonchrome](https://user-images.githubusercontent.com/41024075/55182807-18ff5480-5154-11e9-88ab-dc07de43e454.png)
Firefox
![smallatoms](https://user-images.githubusercontent.com/41024075/55182816-1ef53580-5154-11e9-8e8c-40d065bcd0f5.png)

**Troubleshooting information (do not edit):**

<details>

Name: ‪Molecule Shapes: Basics‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes-basics/1.2.0-rc.2/phet/molecule-shapes-basics_all_phet.html
Version: 1.2.0-rc.2 2019-03-28 11:22:39 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by kathy-phet** [comment]
Confirmed this bug. And it is not present in the currently published version. @jonathanolson - Can you take a look at what is causing this?

**Comment by KatieWoe** [comment]
Looks good in the two rcs
