### ISSUE TITLE
User suggestions: diatomic / polyatomic molecules, library of elements, connection distance

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecule-shapes#171]
> 1) Allow the creation of diatomic or polyatomic molecules in the “Model” module;
>  
> 2) In the module “Real Molecules” include a library of chemical elements (H, He, Li, Be, B, C, ...) and allow new molecules to be created by the user;
>  
> 3) Include in the “Real Molecules” module the connection distance (Ex .: H2, H-H = 0.074 nm)

**Comment by arouinfar** [comment]
Some of the user's goals might be met by the Build a Molecule sim. On the Playground screen, users can build a molecule, and then see its 3D structure as either a space-filling or ball-and-stick representation. 

BAM doesn't allow more than 4 bonds per atom, and is limited by the kits on each carousel page, but there are still 9000+ structures that can be built and inspected in 3D.

@oliver-phet can you share the BAM prototype with this user?

**Comment by oliver-phet** [comment]
Email sent, closing for now.
