### ISSUE TITLE
User reported issue: missing central atom

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/molecule-shapes#172]
> The molecule shapes sim is not showing a central atom to build a molecule on
> 
> ![image](https://user-images.githubusercontent.com/5090275/102271892-2edf1b00-3edd-11eb-94c2-950afffb3d86.png)
> Name: ‪Molecule Shapes‬
> URL: https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html
> Version: 1.2.8 2019-10-28 20:44:43 UTC
> Features missing: applicationcache, applicationcache, touch
> User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
> Language: en-US
> Window: 1646x786
> Pixel Ratio: 1/1
> WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
> GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
> Vendor: WebKit (WebKit WebGL)
> Vertex: attribs: 16 varying: 32 uniform: 768
> Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
> Max viewport: 16384x16384
> OES_texture_float: true

**Comment by jonathanolson** [comment]
It's quite unclear to me what's going on. Might be a WebGL display issue. Might be the older version of Safari (maybe something's in the console). @ariel-phet thoughts, and should we see if we have a similar device/browser combo to test?

**Comment by oliver-phet** [comment]
I did send the user the webGL disabled link to verify if this is a webGL issue. But I'm not sure what else might be causing. I didn't notice anything outdated/unsupported in the user agent info.

**Comment by ariel-phet** [comment]
@oliver-phet can you also gather exact platform from the user if possible? You might also suggest something like clearing their cache (although that seem unlikely to cause an issue). Also perhaps inquire if the sim has worked for them before? As @jonathanolson pointed out it would be good to know if any sort of error is being thrown in the browser console. 

Considering the popularity of this simulation, and the rarity of such a bug report, it seems very platform specific, and probably something we cannot easily address.

**Comment by oliver-phet** [comment]
I haven't heard back from this user after asking for more information. Closing for now.
