### ISSUE TITLE
PhET-iO Design Review

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#175]
For https://github.com/phetsims/special-ops/issues/190

* Rename the following phetioIDs to be a better match to the strings in the sim and/or be more understandable. (For simplicity, the other change requests in this issue will refer to the original phetioIDs.)
  - [x] `moleculeShapes.modelMoleculesScreen` > `moleculeShapes.modelScreen`
  - [x] `moleculeShapes.*.model.showElectronShapeNameProperty` > `moleculeShapes.*.model.showElectronGeometryProperty`
  - [x] `moleculeShapes.*.model.showMolecularShapeNameProperty` > `moleculeShapes.*.model.showMoleculeGeometryProperty`
  - [x] `moleculeShapes.*.view.domNode` > `moleculeShapes.*.view.moleculeNode`
  - [x] `moleculeShapes.*.view.geometryNamePanel` > `moleculeShapes.*.view.namePanel`
  - [x] `moleculeShapes.*.view.geometryNamePanel.electronCheckbox` > `moleculeShapes.*.view.namePanel.electronGeometryCheckbox` 
  - [x] `moleculeShapes.*.view.geometryNamePanel.molecularCheckbox` > `moleculeShapes.*.view.namePanel.moleculeGeometryCheckbox` 
  - [x] `moleculeShapes.realMoleculesScreen.view.moleculePanel.comboBox` > `moleculeShapes.realMoleculesScreen.view.moleculePanel.moleculeComboBox`
  
* These are nested in the wrong place
     - [x] `moleculeShapes.modelMoleculesScreen.view.bondingPanel.lonePairNode` should be under `view.lonePairPanel`
     - [x]  The contents of `moleculeShapes.realMoleculesScreen.view.optionsNode` should all be under `view.optionsPanel`
 
* The model should be the only thing controlling these, so make them phetioReadOnly: true
   - [x] `moleculeShapes.modelMoleculesScreen.view.bondingPanel.*.removeButton.visibleProperty`  (including `lonePairNode.removeButton.visibleProperty` which is currently incorrectly nested here)
   - [x] `moleculeShapes.modelMoleculesScreen.view.optionsPanel.showLonePairsCheckbox.enabledProperty`

* Uninstrument the following
    - [x] `moleculeShapes.modelMoleculesScreen.view.removeAllButton.textNode` -- button doesn't resize with text length which can look bad
    - [x] `moleculeShapes.*.view.geometryNamePanel.*Text` -- the state of the corresponding checkbox should determine if the text is visible

* All panels should have a titleNode with a visibleProperty and textProperty.
    - [x] `moleculeShapes.modelMoleculesScreen.view.bondingPanel`
    - [x] `moleculeShapes.*.view.geometryNamePanel`
    - [x] `moleculeShapes.modelMoleculesScreen.view.lonePairPanel`
    - [x] `moleculeShapes.*.view.optionsPanel`
    - [x] `moleculeShapes.realMoleculesScreen.view.moleculePanel`
 
- [x] Dynamic layout looks strange in `moleculeShapes.*.view.optionsPanel`. The panel width can change when checkboxes are hidden, which shouldn't be happening.
- [x] On the Model screen, the doubleBondNode, singleBondNode, tripleBondNode, and lonePairNode needs something that tells the client that the button has been pressed (not sure if firedEmitter or pressListener is more appropriate here).
- [x] Create a new Property for the molecule geometry and electron geometry (e.g. `model.moleculeGeometryProperty` and `model.electronGeometryProperty`)  that is an enum of the legal geometeries.  
- [x] Seems like the radio buttons on the Real Molecules screen should be in a group. Please group them in `realMoleculesScreen.view.realModelRadioButtonGroup`.

**Comment by jonathanolson** [comment]
I believe I've patched these up, and also made quality of life changes to assorted things that wouldn't have been testable before (e.g. visibility/text changes for panel titles, layout).

CT should hopefully be passing for this next bit.

Link is https://phet-dev.colorado.edu/html/molecule-shapes/1.3.0-dev.3/phet-io/

**Comment by arouinfar** [comment]
In the 4/1/20 design meeting, we discussed https://github.com/phetsims/molecule-shapes/issues/175#issuecomment-811299274 and decided not to pursue any further changes. After taking a look at the things in the state wrapper, the contents of `moleculeShapes.*.model` look good and capture the relevant information. We do not need to create a `model.moleculeProperty`. 

@jonathanolson I reviewed 1.3.0-dev.4 in studio and things are generally looking great, just a few things:

- [ ] The contents of `moleculeShapes.realMoleculesScreen.view.optionsPanel.optionsNode` don't need to be collected in `optionsNode`, they can instead be direct children of `optionsPanel`.
   <img src="https://user-images.githubusercontent.com/8419308/113376442-fd287d80-932e-11eb-9247-e1aea427ea35.png" width=200>

- [ ] `moleculeShapes.*.view.optionsPanel.showLonePairsCheckbox.enabledProperty` should be phetioReadOnly: true
- [ ] `moleculeShapes.*.view.optionsPanel.showLonePairsCheckbox.visibleProperty` should be phetioReadOnly: false
- [ ] If one of the geometry checkboxes is checked and its visibleProperty is set to false, the geometry string below it remains visible. We previously uninstrumented these strings, but that seems like a mistake. Perhaps there should be a `moleculeShapes.*.view.namePanel.*GeometryText.visibleProperty` which is read-only and listens to the visibleProperty of the corresponding checkbox. 
   <img src="https://user-images.githubusercontent.com/8419308/113377300-26e2a400-9331-11eb-91b1-e7016c5ab30a.png" width=250> 
- [ ] Apply dynamic layout to the `namePanel` on both screens. Currently removing one of the checkboxes leaves a hole:
   <img src="https://user-images.githubusercontent.com/8419308/113377786-90af7d80-9332-11eb-9d39-c9e55f62ce47.png" width=250>

**Comment by arouinfar** [comment]
@jonathanolson everything looks good in master. We decided to address the dynamic layout of the `namePanel` in the production release, so we can proceed with the rc-research.

**Comment by jonathanolson** [comment]
Commit above (and multiple common code commits in scenery) have the name panel working nicely, @arouinfar can you verify?

**Comment by arouinfar** [comment]
Looks great, thanks @jonathanolson!
