### ISSUE TITLE
Playback wrapper lag

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#177]
I just want to note, that like with some other sims, this sim has some mildy slow performance in the playback wrapper. It's not the worst I've seen, admittedly, but I just want to make note of it. It really just looks like the playback is being played in slow motion when dragging bonds around. Note that in reality my mouse was moving much quicker than what you see below:

![MS01](https://user-images.githubusercontent.com/5863899/113461855-91501e80-93db-11eb-90d5-67a13632fcd6.gif)

Seen on Win 10 Chrome. For phetsims/QA/issues/635.

**Comment by liam-mulhall** [comment]
Not seeing this on macOS + Safari.

**Comment by jonathanolson** [comment]
@zepumph I think it was discussed that playback performance wasn't something to optimize, correct? (The approach definitely rebuilds the view)

**Comment by zepumph** [comment]
Yes. I have not yet recommended any time to solve this in the past, and I don't think @samreid has either. In my opinion, the playback wrapper is a tool that we use to ensure that the recording are complete. It also serves as an example of what PhET-iO can accomplish. I don't think time needs to be devoted to this issue personally.

**Comment by zepumph** [comment]
We won't be supporting the playback wrapper anymore, see https://github.com/phetsims/phet-io/issues/1854. Closing
