### ISSUE TITLE
Molecule drag is not interrupted when released out of frame

### ISSUE THREAD

**Issue by phet-steele** [phetsims/molecule-shapes#179]
Tested during phetsims/QA/issues/642 but originally reported in https://github.com/phetsims/QA/issues/630#issuecomment-811344484, what is described in that comment still occurs, but there was never any explanation as to why it happens or if this needs to be fixed. (Found on Win 10 Chrome) I'm making this issue now for more proper documentation. 👍

**Comment by jonathanolson** [comment]
Patched, will wait on QA.

**Comment by phet-steele** [comment]
Seems to work well enough in phetsims/QA/issues/649.
