### ISSUE TITLE
PhET-iO Design Comments - Round 2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#188]
@jonathanolson @zepumph here are the remaining issues for Molecule Shapes (and Basics) that I mentioned in PhET-iO meeting. Feel free to split these off into separate issues, as necessary.

- [x] Add documentation to `model.moleculeQuaternionProperty`
- [ ] When selecting `*Screen.model` in Studio, you can see the initial value. Can we also display the current value?
- [x] Make `removeButton.enabledProperty` phetioReadOnly: true (should be model controlled, not user controlled)
- [x] Rename `maxPairsProperty` to `maxConnectionsProperty` and make it a public query parameter called `maxConnections`.
- [x] Add `labelText` to all checkboxes so that the client can change the strings.

<b>EDIT:</b> Please note that these requests all also apply to molecule-shapes-basics.

**Comment by zepumph** [comment]
@jonathanolson, please let me know if I can be of any assistance here, or if I should take over.

**Comment by jonathanolson** [comment]
> Add labelText to all checkboxes so that the client can change the strings.

I didn't immediately adjust the projector-mode checkbox (as that's across other sims), should I add it to that?

**Comment by jonathanolson** [comment]
> When selecting *Screen.model in Studio, you can see the initial value. Can we also display the current value?

@zepumph I'm not sure how to handle this, how do we show current state (instead of initial state) in studio?

**Comment by jonathanolson** [comment]
Besides the above comments, I've implemented the changes. @arouinfar can you verify?

**Comment by arouinfar** [comment]
I want to feature `labelText.textProperty` in the overrides, so leaving this open and self-assigned.

**Comment by arouinfar** [comment]
I updated the description of `maxConnections` in the client guides and featured `labelText.textProperty` for  checkboxes. @jonathanolson once #182 is wrapped up, we're ready to proceed to QA. Closing.
