### ISSUE TITLE
Bond Angles Missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#191]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/715
https://github.com/phetsims/qa/issues/716

In the Model and Real Molecules Screens, the Bond Angles are not shown when the checkbox is checked. 

**Visuals**
<img width="456" alt="Screen Shot 2021-10-08 at 8 11 21 AM" src="https://user-images.githubusercontent.com/87318828/136554660-185ae2da-a84e-436d-8589-0de261f2ea78.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet/molecule-shapes_all_phet.html
Version: 1.4.0-dev.1 2021-10-07 21:09:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1199x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
Should be fixed in master (although there seems to be another unrelated layout issue).

@Nancy-Salpepi can you confirm?

**Comment by Nancy-Salpepi** [comment]
@jonathanolson this looks fixed in master for both molecule shapes and molecule shapes basics.

**Comment by jonathanolson** [comment]
Thanks!
