### ISSUE TITLE
Panels cover molecule and button using stringTest=long

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#192]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
Safari

**Problem description**
https://github.com/phetsims/qa/issues/715

Using stringTest=long:
1. In the Model Screen, the molecule is partially covered by the panels. 
2. In the Real Molecules Screen, the Model Button and the Molecule Panel overlap. 

**Visuals**
<img width="605" alt="Screen Shot 2021-10-08 at 9 12 17 AM" src="https://user-images.githubusercontent.com/87318828/136565094-0ccfedce-d163-41eb-965d-f469f2f2b6b2.png">

<img width="747" alt="Screen Shot 2021-10-08 at 9 21 03 AM" src="https://user-images.githubusercontent.com/87318828/136565141-a9f8cedb-fa57-4955-8407-a24afaf31987.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet/molecule-shapes_all_phet.html
Version: 1.4.0-dev.1 2021-10-07 21:09:50 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15
Language: en-US
Window: 1199x675
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
Should be working well with stringTest=long (ensure pulling sun if using phettest). Can you verify?

**Comment by Nancy-Salpepi** [comment]
Hey @jonathanolson! None of the side panels cover the molecule or model button anymore. The bottom panel seems to get unusually wide with stringTest=long. I feel like usually, the text gets really small, to the point of being unreadable, instead of the panel get extremely large. 
There are a few instances where this panel overlaps the molecule in both stringTest=long and stringTest=double, but they aren't as severe like in my original comment. 
<img width="1173" alt="Screen Shot 2021-11-04 at 2 18 53 PM" src="https://user-images.githubusercontent.com/87318828/140398923-2adb6561-2002-498a-a7db-bd5e3adfb36a.png">
<img width="1173" alt="Screen Shot 2021-11-04 at 2 23 33 PM" src="https://user-images.githubusercontent.com/87318828/140398937-2b9530fa-f686-4661-882b-32d2b70353b4.png">

**Comment by jonathanolson** [comment]
@arouinfar, how much should I limit the size of the panels? It looks like that example also will go "behind" the model/real radio buttons.

**Comment by arouinfar** [comment]
@jonathanolson I think there could have been a regression. The max widths all look reasonable with `stringTest=long`in the published version:
![Screenshot Capture - 2021-11-16 - 15-10-42](https://user-images.githubusercontent.com/8419308/142074153-45df65c6-00c6-401a-aded-bae65d1b76ae.png)

**Comment by jonathanolson** [comment]
This is the current behavior after fixes:
![image](https://user-images.githubusercontent.com/480878/142319181-b8c714a0-65e6-4bed-9164-2630c45e86b5.png)

However the behavior described in https://github.com/phetsims/molecule-shapes/issues/192#issuecomment-961312406 is still broken on the production version:
![image](https://user-images.githubusercontent.com/480878/142320603-73995b4f-a6da-4daa-aa17-49e491a24ac4.png)

**Comment by jonathanolson** [comment]
For reference, I've added a maxWidth on the panel title (mainly for other things, but it applies here).

So... is that acceptable overlap on the bottom panel? Is there anything I should do here?

**Comment by arouinfar** [comment]
> So... is that acceptable overlap on the bottom panel? Is there anything I should do here?

Yes, I think so. The overlap doesn't fully hide the structure, and the molecule can be rotated to remove the overlap
![image](https://user-images.githubusercontent.com/8419308/142464530-d0a29710-8788-495e-9e7f-1dd5729743fc.png)

**Comment by jonathanolson** [comment]
Ok, will mark as ready for QA then (if there's something to do, reassign me).

**Comment by Nancy-Salpepi** [comment]
Looks good.
