### ISSUE TITLE
Console errors when 'Options' is selected in PhET-iO menu

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#193]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
safari 15

**Problem description**
https://github.com/phetsims/qa/issues/715

In the State Wrapper, with the query parameter ?phetioDebug, console errors appear when 'options' is selected in the PhET-iO menu. Once that occurs, the downstream sim will no longer respond to any changes made in the upstream sim.  

**Steps to reproduce**
1. Open State wrapper and console
2. Add ?phetioDebug to url
3. Open the PhET-iO menu and select 'Options' --console errors will appear
4. Exit out of menu, make changes to sim --nothing happens downstream

**Visuals**
<img width="559" alt="Screen Shot 2021-10-09 at 9 19 06 AM" src="https://user-images.githubusercontent.com/87318828/136659928-03b73562-2ec6-4ded-9d30-edef2e7b690e.png">

**Comment by jonathanolson** [comment]
Good find! I think the above commit should fix this, can you verify in master?

**Comment by jonathanolson** [comment]
Thanks!
