### ISSUE TITLE
Only display outer lone pairs if "Show Outer Lone Pairs" and "Show Lone Pairs" are checked

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#194]
The checkbox for 'show outer lone pairs' is currently in the Options dialog found in the PhET menu. 
This means that this option is not affected by the Reset All button (and the location seems odd in general).
Perhaps move to Options Panel and couple with 'show loan pairs?'

In studio, I also don't see anywhere in the tree that would change the visible property of the 'Show Outer Lone Pairs' checkbox to hide it from students. All I see is:
<img width="431" alt="Screen Shot 2021-10-12 at 2 53 31 PM" src="https://user-images.githubusercontent.com/87318828/137012914-6dcb0658-a9a9-4df0-80f7-30b55e825430.png">

which just checks/unchecks the property.

**Comment by jonathanolson** [comment]
Implemented above, @arouinfar can you verify?

**Comment by arouinfar** [comment]
Thanks @jonathanolson it looks like all lone pairs respect the "Show Lone Pairs" checkbox within the sim. However, something strange is going on with the `enabledProperty` of the checkbox itself.  The "Show Lone Pairs" checkbox is only enabled for molecules that have lone pairs on the central atom. This can lead to odd situations where there are lone pairs in the molecule, but the checkbox is disabled (such as CO2 or BF3). 

In my opinion, it's not necessary to disable the checkbox for molecules that do not contain lone pairs. Can you instead leave "Show Lone Pairs" always enabled regardless of the selected molecule?

**Comment by jonathanolson** [comment]
Changed above, can you verify?

**Comment by arouinfar** [comment]
Looks good in master, thanks @jonathanolson. Not sure if you want this verified in the next QA cycle too or not, so back to you.

**Comment by jonathanolson** [comment]
I'm fine closing, thanks!
