### ISSUE TITLE
Mirror Wrapper not working properly

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#195]
**Test device**
MacBook Air (m1 chip)

**Operating System**
11.6

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/715
https://github.com/phetsims/qa/issues/716

The mirror image does not always match the original sim. 

**Steps to reproduce**
1. Select the Model Screen
2. Select 'Remove All'
3. Check 'Show Bond Angles'
4. Add a single bond and then another--they two sims will no longer match
5. Rotate around, add more bonds--sims won't match

**Visuals**
![mirrormolecules](https://user-images.githubusercontent.com/87318828/137018205-9da3f13a-0edc-416f-a461-d53c63d744b5.gif)

**Comment by KatieWoe** [comment]
I saw this in basics as well, and in the recording wrapper. It seems to occur when dragging the central atom as well for me.
<img width="619" alt="mirroroff" src="https://user-images.githubusercontent.com/41024075/139509188-e48566bd-82bd-4eed-a918-3c44951f191f.png">

**Comment by jonathanolson** [comment]
Fixed in the tagged issue. Can you verify?

**Comment by KatieWoe** [comment]
The part I saw looks ok on master. @Nancy-Salpepi I'll leave the rest of the conformation to you.

**Comment by Nancy-Salpepi** [comment]
My part looks good on master as well @jonathanolson

**Comment by KatieWoe** [comment]
This is looking ok so far in rc.1, but since mirror wrapper was replaced with Input Record and Playback it is a bit harder to tell.

**Comment by KatieWoe** [comment]
Looks ok in rc.1. Closing. Will reopen if something comes up.
