### ISSUE TITLE
Lone pair orientation inconsistent 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#196]
**Test device**
MacBook Air (m1 chip) and Chromebook

**Operating System**
iOS 11.6 

**Browser**
chrome

**Problem description**
https://github.com/phetsims/qa/issues/715

In the Real Molecules Screen, when switching back and forth between 'real' and 'model' several times, the orientation of the lone pairs changes--meaning, where they are located the first time 'real' is selected may not be the same as the second time 'real' is selected. 

**Steps to reproduce**
1. Select the Real Models Screen
2. Check 'Show Outer Loan Pairs' in Options under the PhET menu
3. Select a molecule whose terminal atoms have lone pairs, ex. BF3 or XeF4
4. Switch back and forth several times between 'real' and 'model' modes

**Visuals**
![lonepairpositioning](https://user-images.githubusercontent.com/87318828/138286386-2c3bee0b-e485-4789-954d-ccc13497130e.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-dev.1/phet/molecule-shapes_all_phet.html
Version: 1.4.0-dev.1 2021-10-07 21:09:50 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36
Language: en-US
Window: 1431x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jonathanolson** [comment]
@arouinfar, any idea how much time this is worth tracking down? It probably isn't terribly easy to solve.

**Comment by arouinfar** [comment]
@jonathanolson this looks pretty minor to me. If there isn't a clear and easy solution, I'm fine with closing as wontfix.
