### ISSUE TITLE
'Remove All' button does not stay disabled in Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#198]
**Test device**
 iPad Air 2

**Operating System**
15.1

**Browser**
safari

Also seen with MacBook Air OS 12.0.1 + chrome

**Problem description**
https://github.com/phetsims/qa/issues/715
https://github.com/phetsims/qa/issues/716

After disabling the 'Remove All' button in Studio, the button becomes enabled once another bond is added to the molecule. 

**Steps to reproduce**
1. Go to moleculeShapes.modelScreen.view.removeAllButton.enabledProperty and uncheck 'selected' checkbox to disable
2. Add another bond to the molecule -- the checkbox becomes enabled again
OR
1. Go to moleculeShapes.modelScreen.view.removeAllButton.enabledProperty and uncheck 'selected' checkbox to disable
2. Press 'Preview Sim'
3. Add another bond to the molecule

**Visuals**
![removeall](https://user-images.githubusercontent.com/87318828/139715159-572d1f59-95f8-4ed6-a7bb-0b10c4eae85b.gif)

**Comment by jonathanolson** [comment]
@arouinfar This is a case where whether the button is enabled is determined by the sim. Should we create a new Property to determine whether the button CAN be enabled?

**Comment by arouinfar** [comment]
@jonathanolson I think in this case we can make the button's `enabledProperty` phetioReadOnly: true. The model should be controlling this property, not the client. If a client wants to prevent users from using this button, they can hide it instead.

**Comment by jonathanolson** [comment]
Should be handled above.

**Comment by KatieWoe** [comment]
Looks good in rc.1
