### ISSUE TITLE
Extra bond angle label 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#202]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/745

In the Real Molecules Screen, for ClF3, the sum of the two bond angles (or the distance between the 2 outermost atoms) is shown faintly. I don't see this with any other molecules. 

**Visuals**
<img width="414" alt="Screen Shot 2021-11-27 at 12 10 14 PM" src="https://user-images.githubusercontent.com/87318828/143692226-108f10a2-0d5e-4781-8fc4-56ab6cba82de.png">

<img width="412" alt="Screen Shot 2021-11-27 at 1 14 05 PM" src="https://user-images.githubusercontent.com/87318828/143699167-1bfc501a-174d-434b-a4b8-189acb67fa37.png">

Compare to BrF5 and XeF4:

<img width="417" alt="Screen Shot 2021-11-27 at 1 15 47 PM" src="https://user-images.githubusercontent.com/87318828/143700396-482d4ac5-5670-4b0f-91ea-f204fe6580f5.png">

<img width="494" alt="Screen Shot 2021-11-27 at 12 56 31 PM" src="https://user-images.githubusercontent.com/87318828/143694910-9557ffab-9b55-4844-802e-9d7cf24133c5.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-rc.1/phet/molecule-shapes_all_phet.html
Version: 1.4.0-rc.1 2021-11-24 02:29:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36
Language: en-US
Window: 1419x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by DevonQui** [comment]
I was able to recreate this in the Model screen of the sim as well. If you recreate the same T-Shaped molecule that ClF3 is then there will also be an extra bond label. However, you have to jiggle the molecule around or else it won't show up which I thought was a bit peculiar.

<img width="1440" alt="Screen Shot 2021-11-29 at 1 15 46 PM" src="https://user-images.githubusercontent.com/72042459/143936550-aaf9a5a3-244e-4c27-9d99-8cc39d1a4685.png">

**Comment by KatieWoe** [comment]
I was able to reproduce this in the published sim.

**Comment by jonathanolson** [comment]
This looks purely like a result of the formula, which weights a bunch of different things:

```js
  /**
   * Determines the brightness (alpha) of a bond angle based on the orientations of the two radial atoms, the camera,
   * and the total number of bonds around our central atom.
   * @public
   *
   * @param {Vector3} aDir - The unit vector pointing towards the first radial atom
   * @param {Vector3} bDir - The unit vector pointing towards the second radial atom
   * @param {Vector3} localCameraOrientation - A unit vector in the molecule's local coordiante space pointing
   *                                           to the camera.
   * @param {number} bondQuantity - The total number of bonds around the central atom
   */
  static calculateBrightness( aDir, bDir, localCameraOrientation, bondQuantity ) {
    // if there are less than 3 bonds, always show the bond angle.
    if ( bondQuantity <= 2 ) {
      return 1;
    }

    // a combined measure of how close the angles are AND how orthogonal they are to the camera
    const brightness = Math.abs( aDir.cross( bDir ).dot( localCameraOrientation ) );

    const lowThreshold = BondAngleView.LOW_THRESHOLDS[ bondQuantity ];
    const highThreshold = BondAngleView.HIGH_THRESHOLDS[ bondQuantity ];

    const interpolatedValue = brightness / ( highThreshold - lowThreshold ) - lowThreshold / ( highThreshold - lowThreshold );

    return Utils.clamp( interpolatedValue, 0, 1 );
  }
```

It should be possible to adjust the threshold of what's visible slightly in the 3-bond case (there are tweakable thresholds). This would presumably affect all bond angle visibility when there are 3 bonds if we tweak it:
```js
// dot product between the camera direction and bond angle normal is below LOW_THRESHOLDS[bondOrder] => alpha = 0
// dot product between the camera direction and bond angle normal is above LOW_THRESHOLDS[HIGH_THRESHOLDS] => alpha = 1
BondAngleView.LOW_THRESHOLDS = [ 0, 0, 0, 0, 0.35, 0.45, 0.5 ]; // @public
BondAngleView.HIGH_THRESHOLDS = [ 0, 0, 0, 0.5, 0.55, 0.65, 0.75 ];
```

**Comment by jonathanolson** [comment]
I made a slight threshold change, which does affect visibility in the general 3-bond case as seen here:

Before:
![image](https://user-images.githubusercontent.com/480878/147595908-89ed2fd9-be0d-47ef-8f78-62c10e2d7c42.png)

After:
![image](https://user-images.githubusercontent.com/480878/147595932-d7771dc7-99ac-4223-8552-69eb57edaf92.png)

But that removes the ClF3 "overlap" one completely.

@arouinfar let me know if this is sufficient.

**Comment by arouinfar** [comment]
@jonathanolson looks reasonable to me. The opacity of the bond angle labels is most affected when looking at the molecule with a very skewed perspective. Shifting the molecule slightly will increase the readability of the labels.

![image](https://user-images.githubusercontent.com/8419308/148127183-78e4aa15-2c4f-4d02-b882-601548b1adcc.png)

**Comment by jonathanolson** [comment]
Ok thanks, closing!
