### ISSUE TITLE
Many credits gone

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#204]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/745.
Most of the credits in the About section seem to be gone. Compare to V. 1.2, which is currently published.

**Visuals**
<img width="644" alt="12credits" src="https://user-images.githubusercontent.com/41024075/143957142-fe5af53d-a74d-4639-bae4-7df265beceaa.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.4.0-rc.1/phet/molecule-shapes_all_phet.html?showPointerAreas
Version: 1.4.0-rc.1 2021-11-24 02:29:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details

**Comment by KatieWoe** [comment]
Also seems to occur on basics

**Comment by arouinfar** [comment]
Really great find @KatieWoe. Looks like the credits were updated in April 2019 in these commits https://github.com/phetsims/molecule-shapes/commit/5b6acdd1e382555ac824f2a10c45dbc104b5fa70 and https://github.com/phetsims/molecule-shapes/commit/d5b3ea6defa13762e6fadec8d33eedf04d98017f, but they were only applied to the 1.2 branch, not master.

@jonathanolson I went ahead and fixed the credits in master and 1.4 in the above commits, including QA testers for the current RC cycle.

**Comment by arouinfar** [comment]
I updated the credits in Basics in the above commits.

**Comment by jonathanolson** [comment]
Thanks! Branches and master looks good, unassigning and marking for review for next RC (presumably)

**Comment by jonathanolson** [comment]
Added in master. Everything look good here?

**Comment by KatieWoe** [comment]
Looks good
