### ISSUE TITLE
Swap order of electron geometry and molecule geometry checkboxes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#211]
Discussed in the 1/20/22 design check-in and we decided to proceed with this change.

User suggestion:
> NEW COMPLAINT: PhETsims on the Molecule Shapes simulation Electron Geometry should be listed first because you think of the overall domains before you think of specific bonding domains or lone pairs. Also, Electron Geometry determines angle. 

I couldn't find an explicit reason for the order of the checkboxes in the sim documentation, but @kathy-phet reached out to Trish who wrote back:
> I just looked at my lesson and I definitely had my students Use the molecular geometry to figure out that lone pairs change it. This makes sense to me because books show the actual molecular geometry and then try to explain using lone pairs how it works. I think this teacher must be teaching electron configuration first and then using that to make sense of molecules. To me this seems like a harder way for students to understand. I’ll email you my lesson
>By the way before Phet I would’ve had to do the electron configuration first because the students had to pick the right real ball With the right number of holes before they could use the sticks. Phet made this so much more a discovery experience:bulb:

The [OpenStax chem textbook](https://openstax.org/books/chemistry-2e/pages/7-6-molecular-structure-and-polarity) introduces electron geometry before molecular geometry and I have seen several variations on this diagram that show how molecule geometry is derived from electron geometry:
<img src="https://user-images.githubusercontent.com/8419308/150622747-0ba2c927-ec71-4c54-bced-519c78844594.png" width=400>

@Nancy-Salpepi commented over Slack:
> It absolutely makes sense to have electron geometry come first. Your recollection is correct--in VSPER it comes first and then the molecular geometry is determined based on bonding and nonbonding pairs. I think it is a really good suggestion!

**Comment by jonathanolson** [comment]
Implemented above, can you verify?

**Comment by arouinfar** [comment]
Looks good @jonathanolson
