### ISSUE TITLE
Pointer Area too large

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#212]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/768, the pointer area for molecule geometry is too large. This is on both screens.

**Steps to reproduce**

**Visuals**
![pointerareasize](https://user-images.githubusercontent.com/87318828/150820099-ea9e5403-5ffe-46a5-a601-4ad24145fe9e.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.5.0-dev.3/phet/molecule-shapes_all_phet.html?showPointerAreas
Version: 1.5.0-dev.3 2022-01-22 22:59:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Language: en-US
Window: 1409x687
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by Nancy-Salpepi** [comment]
The size of the Molecule Geometry pointer area changes as more bonds/lone pairs are added. If I click in that overlap area, only the electron geometry checkbox is changed. 

<img width="653" alt="Screen Shot 2022-01-24 at 11 30 28 AM" src="https://user-images.githubusercontent.com/87318828/150825044-628163ba-8c2e-42c2-8c1f-9bf314b08792.png">
<img width="497" alt="Screen Shot 2022-01-24 at 11 32 12 AM" src="https://user-images.githubusercontent.com/87318828/150825077-838f483a-8869-4c62-bee3-e778285529d1.png">

**Comment by jonathanolson** [comment]
I believe this should be fixed in master. Can you verify?

**Comment by Nancy-Salpepi** [comment]
Yup...all fixed!

**Comment by jonathanolson** [comment]
Thanks!
