### ISSUE TITLE
Show Lone Pairs checkbox behaves differently

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#214]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/768. The Show Lone Pairs checkbox behaves differently than in published. In published, on the first screen it is on and disabled until you add a pair. If there are no pairs it reverts to this state. However, now the checkbox is not disabled. Not sure what behavior is desired, but it is different.

**Visuals**
Published:
![oldbehavior](https://user-images.githubusercontent.com/41024075/150882923-1286364e-8296-41c4-bb83-7f126b2a7c85.gif)
Dev test:
![newbehavior](https://user-images.githubusercontent.com/41024075/150882943-8bc5d4bc-a276-4f26-855d-7a7e5042bf6d.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Molecule Shapes‬
URL: https://phet-dev.colorado.edu/html/molecule-shapes/1.5.0-dev.3/phet/molecule-shapes_all_phet.html
Version: 1.5.0-dev.3 2022-01-22 22:59:16 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0
Language: en-US
Window: 1280x667
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.100.9955))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jonathanolson** [comment]
@arouinfar thoughts? We decided to not change the checkbox state without user input, do we want to change the initial behavior? I think this looks like the desired behavior as described to me.

**Comment by arouinfar** [comment]
Thanks for reporting @KatieWoe.

The behavior was changed as a result of #194 and #201 and looks correct in 1.5.0-dev.3, so closing.
