### ISSUE TITLE
Delete IE11StencilWarningNode, because IE is no longer supported.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#217]
From the CRC:

> - [ ]  IE is no longer supported. With that in mind remove IE-specific workarounds

So can IE11StencilWarningNode.js be deleted, instead of spending the effort to convert to TS? 

IE11StencilWarningNode.js was writting by @jonathanolson, and is used exclusively in molecule-shapes.  So assigning to him.

**Comment by pixelzoom** [comment]
I transferred this issue from scenery-phet to molecule-shapes. And I moved IE11StencilWarningNode.js to molecule-shapes, where you can delete it at your leisure.

**Comment by jonathanolson** [comment]
Committed above, thanks! Closing.
