### ISSUE TITLE
Panel width should expand if panel title is long

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#224]
Related to #223 

When making the panel titles long, they seem to escape the `maxWidth` of the panel. I had to widen the sim window to pull these strings within view. They originally escaped the window bounds.
![image](https://user-images.githubusercontent.com/8419308/194591120-60be65b5-7252-47e6-8ace-3e0335876cb4.png)

Affected strings:
`strings.moleculeShapes.control.bondingStringProperty`
`strings.moleculeShapes.control.lonePairStringProperty`
`strings.moleculeShapes.control.optionsStringProperty`
`strings.moleculeShapes.control.moleculeStringProperty`

It seems like the string `maxWidth` is based on the associated panel `maxWidth`, but that width is only realized if the panel contents expand. 
![image](https://user-images.githubusercontent.com/8419308/194593070-5141cfbd-145e-4c61-9e07-be4eb8113689.png)

@jonathanolson it seems like the panel should expand when the title is long, not just when the contents are long.

I'll open a side issue for the ComboBox button which is oddly stretched -- see #224

**Comment by arouinfar** [comment]
Tagging for https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.

**Comment by KatieWoe** [comment]
I noticed that this can cause the text to go out of bounds before it starts shrinking.

**Comment by samreid** [comment]
@arouinfar or @KatieWoe is this still a problem?  I tried expanding the Bonding title and saw that it resized the panel:

<img width="315" alt="image" src="https://user-images.githubusercontent.com/679486/208159604-b374e96f-3301-46d8-be48-093d6b669068.png">

Longer strings seemed to shrink at the appropriate point.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/679486/208159681-d6ed5843-d9db-4474-9633-e32a9c318404.png">

Please close if all is well, or specify more about how I can test and observe this.

**Comment by KatieWoe** [comment]
I still see this on master, and strings seem to also go out of bounds to the right.
<img width="949" alt="stillmaster" src="https://user-images.githubusercontent.com/41024075/208184770-90d1d2ec-dfe0-4991-bac3-2b231072dc70.png">

**Comment by samreid** [comment]
I likely missed this since I was editing the _en translation file--so perhaps the startup string length behaves different than changing it at runtime.  I'll re-self-assign.

**Comment by jonathanolson** [comment]
Handled in the above commit, closing!
