### ISSUE TITLE
Add links to `stringProperty` to Real/Model radio buttons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#226]
For #223 

@jonathanolson can you add a link to the appropriate `stringProperty` to `realRadioButton` and `modelRadioButton`?

**Comment by arouinfar** [comment]
Tagging for https://github.com/phetsims/qa/issues/844.

**Comment by zepumph** [comment]
The text is actually the content node of the the radioButton, so we needed substructure and couldn't have the stringProperty as a sibling to radioButton Properties. How is this?

![image](https://user-images.githubusercontent.com/6856943/206564701-dc244bd2-5374-4407-bd63-810341433933.png)

**Comment by arouinfar** [comment]
> The text is actually the content node of the the radioButton, so we needed substructure and couldn't have the stringProperty as a sibling to radioButton Properties. How is this?

Perfect, thanks @zepumph! You read my mind -- the goal was for users to find the appropriate `stringProperty` while they are looking at the radio buttons in the view, and now they can.
