### ISSUE TITLE
Basics: `realMoleculeShapesProperty` includes values that are only valid in the full version

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#227]
Related to #223 

The valid values of `realMoleculeShapesProperty` seems to be the full list of molecules available in Molecule Shapes. If you pass in a value that only appears in Molecule Shapes, Studio will not stop you.

For example, set the value to SF4 and it will appear to work, but the sim encounters a fatal error and freezes.
![image](https://user-images.githubusercontent.com/8419308/194604909-90440716-692f-4230-814d-a63b762d7ea4.png)

@jonathanolson should the validation be limited to the 5 molecules in Molecule Shapes: Basics?

**Comment by arouinfar** [comment]
Tagging for https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.

**Comment by zepumph** [comment]
I was able to get this done by having the Property get validValues to start with. @arouinfar how does that look?

**Comment by arouinfar** [comment]
Thanks @zepumph! Everything looks good in master.
