### ISSUE TITLE
Grammar change needed in PhET-iO guide

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#229]
For https://github.com/phetsims/qa/issues/844

Under: **Loading an Existing Standard PhET-iO Wrapper for Revision, Migration, or Adaptation** section, this sentence could use some rewording:
>Once edited, the file becomes a Custom PhET-iO Wrapper and may no longer be able to reliably load it in PhET-iO Studio for revision nor realize the benefits of version migration support.

Looks like "you" is missing after "and" in the sentence.

**Comment by arouinfar** [comment]
Good catch @Nancy-Salpepi. I've edited that sentence and it now reads:

> Once edited, the file becomes a Custom PhET-iO Wrapper and may no longer reliably load in PhET-iO Studio for revision nor realize the benefits of version migration support.
