### ISSUE TITLE
Opt/Alt doesn't connect to Molecule Node

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#232]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.
The Opt/Alt command to see the View Element connected to an object does not seem to work for the Molecule Node. Other elements in the view tree seem to be selected when moving the mouse over that object, but not with the Molecule node.
**Steps to reproduce**
1. Go to either screen in studio
2. Press Opt/Alt on your keyboard
3. Move the mouse over the central molecule

**Comment by arouinfar** [comment]
@jonathanolson is it possible something was overlooked here? Seems odd that using option doesn't take the user to `view.moleculeNode` in the tree.

I don't think this is a serious UX issue, however. The `moleculeNode` isn't nested all that far down in the tree and isn't particularly hard to find. Hiding the molecule doesn't feel like the most pedagogically valuable customization, either. If there isn't a clear way to hook up the select feature, I'm fine with closing this issue @jonathanolson.

**Comment by samreid** [comment]
We implemented studio autoselect for 3d shapes in Density by adding `getPhetioMouseHit` to `ThreeIsometricNode`.   Molecule Shapes doesn't use ThreeIsometricNode. Instead, it adds a THREE scene in `MoleculeShapesScreenView`. @jonathanolson would know best, but from what I can see this would be difficult or nontrivial.  I tried adding `getPhetioMouseHit` to the `MoleculeShapesScreenView` but it was not called while using studio.

**Comment by arouinfar** [comment]
>  but from what I can see this would be difficult or nontrivial

Thanks @samreid. I'll close this as wontfix. Being able to find the `moleculeNode` using the select feature isn't critical, since it isn't tied to pedagogically important customizations.
