### ISSUE TITLE
Studio geometry listing may not match sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/molecule-shapes#234]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.
When in studio, looking at a molecule's molecule or electron geometry, you may see it is diatomic, but the sim itself says linear. Should these two match?

**Visuals**
<img width="932" alt="diatomicorlinear" src="https://user-images.githubusercontent.com/41024075/198137447-dfc09d11-6f6a-46c3-82bd-fd8dbcf5efe0.png">

**Comment by arouinfar** [comment]
Good catch @KatieWoe.

I've never seen "diatomic" as a molecular geometry. Diatomic atoms have a linear geometry. 

@Nancy-Salpepi have you ever seen diatomic used as a classification of molecular geometry?

**Comment by Nancy-Salpepi** [comment]
@arouinfar I have never seen "diatomic" used as a classification. As you said, they have linear geometry.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. Seems like we should remove "Diatomic" @jonathanolson.

**Comment by jonathanolson** [comment]
The sim needs to differentiate between these internally (since 3 atoms in linear is different than diatomic, it's a fundamentally different structure). Each geometry needs to have a certain number of atoms.

So that might be possible, but it would be a significant refactor internally (many hours at least). How much time would this be worth?

**Comment by arouinfar** [comment]
Thanks for the clarification @jonathanolson. I would be more concerned if `DIATOMIC` appeared instead of `LINEAR` on the Real Molecules Screen. Since the smallest molecule on that screen is triatomic, it doesn't. Let's close.
