### ISSUE TITLE
Ready Molecule Shapes for PhET-iO Publication

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/molecule-shapes#237]
[Dev test](https://github.com/phetsims/qa/issues/844) issues to address to ready Molecule Shapes for Publication
- [ ] https://github.com/phetsims/molecule-shapes/issues/228
- [ ] https://github.com/phetsims/molecule-shapes/issues/227
- [ ] https://github.com/phetsims/molecule-shapes/issues/226
- [ ] https://github.com/phetsims/molecule-shapes/issues/225
- [ ] https://github.com/phetsims/molecule-shapes/issues/224
- [ ] https://github.com/phetsims/scenery/issues/1458
- [x] https://github.com/phetsims/molecule-shapes/issues/229
- [x] https://github.com/phetsims/molecule-shapes/issues/230
- [x] https://github.com/phetsims/gravity-and-orbits/issues/448
- [ ] https://github.com/phetsims/molecule-shapes/issues/231
- [ ] https://github.com/phetsims/scenery-phet/issues/766
- [ ] https://github.com/phetsims/molecule-shapes/issues/232
- [ ] https://github.com/phetsims/molecule-shapes/issues/233
- [x] https://github.com/phetsims/molecule-shapes/issues/234
- [x] https://github.com/phetsims/joist/issues/877
- [ ] https://github.com/phetsims/molecule-shapes/issues/235
- [ ] https://github.com/phetsims/scenery/issues/1501

**Comment by arouinfar** [comment]
I opened #238 to track https://github.com/phetsims/scenery/issues/1458, but the PhET-iO team decided it was non-blocking, so I won't be adding it to the publication milestone.

**Comment by arouinfar** [comment]
All relevant issues have been tagged in https://github.com/phetsims/molecule-shapes/milestone/1, so we can close this issue.
