### ISSUE TITLE
Some characters not rendering correctly in translated sims on Safari

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#238]
Originally reported in https://github.com/phetsims/scenery/issues/1458 and was observed in https://github.com/phetsims/qa/issues/844.

Opening an issue in molecule-shapes so we don't forget about this issue. However, the PhET-iO team decided that this isn't a blocking issue because it appears in currently published sims and will likely require a maintenance release to fix.

**Comment by jonathanolson** [comment]
This should be fixed now, with the recent maintenance release.
