### ISSUE TITLE
Touch outline doesn't reflect touch area with locales other than English 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#239]
Originally reported in https://github.com/phetsims/scenery-phet/issues/766 and was discovered in https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845.

Opening an issue in molecule-shapes to keep track of this issue. Since `showPointerAreas` is an internal tool and the touch behavior is otherwise correct, this isn't a publication-blocking issue.

**Comment by jonathanolson** [comment]
Using VerticalCheckboxGroup now. This needed a new `optionsCheckboxGroup` tandem, and some tandem/structure changes around it. Can you verify?

Otherwise, the touch issue should be fixed (and was a bug)

**Comment by arouinfar** [comment]
Looks good, thanks @jonathanolson
