### ISSUE TITLE
Remove Button location is odd when panel size expands

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#241]
**Test device**
MacBook Air M1 chip

**Operating System**
13.1

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/905: On the Model Screen, with some locales there is an unusually large space between the Lone Pairs image and the Remove button. 

**Steps to reproduce**
Example:
1. Change locale to Swahili
2. Add lone pairs to central atom

**Visuals**
<img width="334" alt="Screenshot 2023-02-21 at 3 46 54 PM" src="https://user-images.githubusercontent.com/87318828/220458319-21ccd714-e3d4-4dd2-9eb2-f6a89926cbd9.png">

**Comment by jonathanolson** [comment]
I think the fix for https://github.com/phetsims/molecule-shapes/issues/242 also fixes this, can you verify?

**Comment by Nancy-Salpepi** [comment]
This looks good in master now, but https://github.com/phetsims/molecule-shapes/issues/242 is not fixed.

**Comment by jonathanolson** [comment]
Please close after verifying!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2! Closing.
