### ISSUE TITLE
Autoselect is sometimes broken when you mouse over something then press ctrl/opt/alt

### ISSUE THREAD

**Issue by arouinfar** [phetsims/molecule-shapes#245]
Related to https://github.com/phetsims/qa/issues/905 and https://github.com/phetsims/qa/issues/906. 

Opening this issue to track https://github.com/phetsims/studio/issues/295.

@jonathanolson there is a MR planned to handle the above studio issue, but it may come before Molecule Shapes is published. If that happens, you'll need to cherry-pick the relevant commits into Molecule Shapes and Molecule Shapes: Basics.

FYI @samreid.

**Comment by samreid** [comment]
@jessegreenberg and I will be collaborating on this issue around 11am MT today

**Comment by zepumph** [comment]
To commit for this issue in molecule shapes:

https://github.com/phetsims/studio/commit/e0ffb2cc1ba7e06abe09b4c09f557f491e26bfc7
https://github.com/phetsims/phet-io-sim-specific/commit/9ab265d27852b33eb278b0c33ad020414baa3406

**Comment by jessegreenberg** [comment]
Hello! sudio#295 also included a fix for chrome stealing focus from alt key, you may need https://github.com/phetsims/studio/commit/5d5d356c7003a7628b0a3cd6810fd4b09e68d511 (`preventDefault call`) and the commits leading up to it.

**Comment by zepumph** [comment]
Sure thing. I didn't include that because Molecule Shapes RC shas were taken from master 2/21.

**Comment by jessegreenberg** [comment]
Ah, excellent, thank you!

**Comment by zepumph** [comment]
- [ ] Don't forget about basics too!

**Comment by jonathanolson** [comment]
Patches applied above, waiting on testing.

**Comment by jonathanolson** [comment]
Please close after verifying!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2 for full/basics versions. Closing.
