### ISSUE TITLE
titleText.visibleProperty switches back to 'true' when locale changes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#246]
**Test device**
MacBook Air M1 chip

**Operating System**
13.2.1

**Browser**
Safari and Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/906 and https://github.com/phetsims/qa/issues/905, for any panel on either screen, if I change the `titleText.visibleProperty` to false and then switch locales, the titles appear again. 
Also seen in the launched sim. 

**Steps to reproduce**
Ex:
1. On the Real Molecules Screen, set moleculeShapes.realMoleculesScreen.view.optionsPanel.titleText.visibleProperty to false.
2. Change to any locale --the titles appear
3. Change back to English --the titles are present. 

**Visuals**

https://user-images.githubusercontent.com/87318828/221282148-3838df9c-eb8e-4758-9a00-056263c9e3c7.mp4

**Comment by jonathanolson** [comment]
I believe I've fixed this up in master (there was some undesirable behavior and code in general). @Nancy-Salpepi can you verify?

**Comment by jonathanolson** [comment]
Please close after verifying!

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.2 for MS and MS:Basics. 
Closing.
