### ISSUE TITLE
"Real Molecules" screen icon image missing or partially missing

### ISSUE THREAD

**Issue by stemilymill** [phetsims/molecule-shapes#247]
For https://github.com/phetsims/qa/issues/905 and https://github.com/phetsims/qa/issues/906

similarities to https://github.com/phetsims/molecule-shapes/issues/161

Seen on Lenovo 100e Chromebook gen 2 with ChromeOS Version 110.0.5481.181 (Official Build) (32-bit). 
I first saw it on 110.0.5481.112 and then updated.

@Nancy-Salpepi does not see this on her chromebook.

I saw this in a private window but cleared my cache just in case that was the issue and there was no change.

The icon for Real Molecules is incomplete on Molecule Shapes and Molecule Shapes: Basics, and I do also see it in published.
For Basics, the model is completely missing, and in Molecule Shapes, the sticks are visible and sometimes fragments of the spheres.

![molecule shapes 1 6 0-rc 1 phetio standalone homescreen icon](https://user-images.githubusercontent.com/85511101/221677294-8b7ea8cc-601a-4f38-bbfd-9215ba9cc423.png)

![molecule shapes basics 1 6 0-rc 1](https://user-images.githubusercontent.com/85511101/221677490-e537ba43-652c-4256-90d2-165e01f52e4d.png)

In the Model screen, the images in the Bonding and Lone Pair panels are sometimes incomplete.

![molecule shapes 1 6 0-rc 1 images](https://user-images.githubusercontent.com/85511101/221678833-7049f85e-ab94-43e9-b673-e2203505192f.png)

An example of alerts in console

![Screenshot 2023-02-27 3 07 49 PM](https://user-images.githubusercontent.com/85511101/221679045-47ad0253-395c-45a6-aa4e-5bdb3c29bc5f.png)

**Comment by jonathanolson** [comment]
@kathy-phet @arouinfar  I don't believe there's much I can try here except for upgrading three.js. This looks like it could be a three.js issue (most likely?), a hardware/support issue, or both.

If I do upgrade, we would lose the ability to render in canvas (currently for this sim, we have the fallback if someone doesn't have GPU support). However we'd be able to use more common code for 3d handling.

Thoughts?

**Comment by kathy-phet** [comment]
@jonathanolson - What is the lift to upgrade three.js? I feel like I recall you considering that previously, but that its a large amount of work. 

@arouinfar - Have we received any reports from teachers on this? 

@stemilymill - Was the sim usable in general? e.g. did you see rendering issues on the actual manipulatable molecule?

**Comment by arouinfar** [comment]
> @arouinfar - Have we received any reports from teachers on this?

No, not that I recall @kathy-phet. I also looked through the repo and didn't see any reports received by phethelp.

**Comment by stemilymill** [comment]
@kathy-phet the sim was definitely usable and I didn't notice any rendering issues with the actual molecule

**Comment by Nancy-Salpepi** [comment]
The Lenovo I have is an older model than @stemilymill's and I am not seeing this issue. I have a Lenovo 100e Chromebook with ChromeOS 110.0.5481.181.

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi @stemilymill. Sounds like this is very device specific and doesn't impact usability of the sim itself. Emily mentions that it occurs in published, but there haven't been any reports into phethelp about this issue, which leads me to believe it is uncommon. Given @jonathanolson's assessment, I think we can leave this as-is, but I'll let @kathy-phet make the final call.

**Comment by kathy-phet** [comment]
Let's close as "will not fix". If we get further reports that make us believe its common, we can re-open. So I'll close it.
