### ISSUE TITLE
Please make phetioReadOnly: false for showLonePairsCheckbox.enabledProperty

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/molecule-shapes#248]
For https://github.com/phetsims/qa/issues/905

Please change `showLonePairsCheckbox.enabledProperty` so that it is `phetioReadOnly: false`

Discussed this with @arouinfar on slack. From Amy:
I think I asked for it to be read-only because it was automatically disabled on startup. That’s no longer relevant.
Good catch! Since the sim no longer automatically disables the checkbox, the enabledProperty doesn’t need to be read-only anymore. Can you open an issue to make it phetioReadOnly: false?

**Comment by jonathanolson** [comment]
Patched up. @Nancy-Salpepi can you verify on master?

**Comment by Nancy-Salpepi** [comment]
Looks good in master. Thanks!

**Comment by jonathanolson** [comment]
Please close after verifying!

**Comment by Nancy-Salpepi** [comment]
Looks good in rc.2. Closing
