### ISSUE TITLE
Molecule Shapes and Molecule Shapes: Basics need a maintenance release

### ISSUE THREAD

**Issue by liammulh** [phetsims/molecule-shapes#252]
@oliver-phet re-opened https://github.com/phetsims/rosetta/issues/390:

> @liammulh the zh_TW translator is still seeing the same issue on 3 sims:
Masses and Springs: Basics
Molecule Shapes: Basics
Molecule Shapes

> All 3 seem to have 2 shared strings that aren't available to translate, but are included in the info statistics (all strings are translated).
![Screenshot_20230408_081345](https://user-images.githubusercontent.com/5090275/230928617-d298e5de-15b4-499b-934b-b6b08b91f2df.png)

Molecule Shapes doesn't have shared strings. The problem is that there are empty strings in Molecule Shapes and Molecule Shapes: Basics — `geometry.empty` and `shape.empty`. These aren't presented to the user for translation, and they aren't counted in the translation statistics.

For more info on the decision to not present empty strings to users, see https://github.com/phetsims/rosetta/issues/388.

**Comment by jbphet** [comment]
The maintenance release is complete, but I wanted to transfer the issue from rosetta to molecule-shapes because that seems like a more reasonable place for it if we ever need to find it.  The parent issue - https://github.com/phetsims/rosetta/issues/388 - is still in the rosetta repo.

**Comment by jbphet** [comment]
This is done - closing.
