### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#60]
Assigned to @pixelzoom at 10/23/14 dev meeting.

Do a quick pass today if possible. Looking for input on what is and isn't worth cleaning up. Do we need more documentation for stuff that's related to Three.js and WebGL?

Then do a more complete review after Nov 5.

**Comment by jonathanolson** [comment]
I'm now waiting on feedback for all review items besides getting the SIL open font license included (#72), which will need to be handled (but I don't believe requires review feedback). Individual questions are in the issues, and all 'REVIEW' items were self-explanatory.

Many thanks for the in-depth code review!

**Comment by pixelzoom** [comment]
All issues are either closed or close to being closed. Code review complete.
