### ISSUE TITLE
Perpetual motion created in certain cases (iOS 7.1/Canvas)

### ISSUE THREAD

**Issue by ycarpenterphet** [phetsims/molecule-shapes#65]
Dev version 9
Test device: iPad2
Operating System: iOS 7.1
Browser: mobile Safari
Problem description: There are several situations where the molecule gets stuck in a perpetual movement cycle on the model screen.

Steps to reproduce:
(1) Start with 2 bonded atoms. Add 4 lone pairs. Lone pairs will wobble back and forth perpetually, rather than finding a stable position. See video clip here:
https://drive.google.com/file/d/0B4Hie_375TsjUU0za3VmT3hyTlE/view?usp=sharing

(2) A molecule with 3 lone pairs and 3 bonded atoms where the lone pairs and the atom in the same plane can be set rotating perpetually. See video clip here:
https://drive.google.com/file/d/0B4Hie_375TsjenRHMHR2TVN2VDg/view?usp=sharing
I haven't been able to reproduce this one, but it cropped up while I was getting ready for a student interview, and we also saw it during the interview as well. 

Severity: High - both issues lead would students to draw conclusions about stability of the molecules that aren't true.

**Comment by jonathanolson** [comment]
Should be fixed, closing.
