### ISSUE TITLE
don't attach properties directly to window

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#68]
molecules-shapes-config.js does this:

> window.loadedMoleculeShapesConfig = true;

I'm still very much opposed to attaching things directly to window. I think anything and everything that PhET attaches should be attached to window.phet.  This would make it much easier to identify what we are attaching, and (unlikely to be an issue in this case) prevent incompatibles with other things that add to window.

That said... If you don't want to address this, that's OK with me. Just pointing it out.

**Comment by jonathanolson** [comment]
Also forgot to tag https://github.com/phetsims/molecule-shapes/commit/5270441f1ffdfae0fd0717e43f9d4534ed67473e to the issue.

**Comment by jonathanolson** [comment]
I've switched to the improved style of dynamically loading the config/main (see https://github.com/phetsims/scenery/issues/344). This makes the 'loaded config' flags and loop unnecessary (it's much cleaner now), and the flags have been removed.
