### ISSUE TITLE
is SIL Open Font License compatible with PhET?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#72]
LiberationSansRegularSubset doc says:

> * Numeric subset of Liberation Sans Regular, used for dynamic text performance (changing 12+ text values per frame was
 * a major bottleneck when using SVG text).
 * (uses the SIL Open Font License, http://en.wikipedia.org/wiki/SIL_Open_Font_License)

Is this license compatible with PhET?

I'm also not clear on what's required to meet the terms of this license. The Wikipedia entry says:

> The license is considered free by the Free Software Foundation, which states that a simple hello world program is enough to satisfy the license's requirement that fonts using the license be distributed with computer software.[2]

**Comment by jonathanolson** [comment]
@samreid, is it possible to add sim-specific licensing information, or do I need to move the data into sherpa?

**Comment by samreid** [comment]
It's not possible at the moment to add sim-specific license information, and it has served us well to keep all 3rd party dependencies in sherpa, please move the font data there as well and annotate in info.js.

**Comment by jonathanolson** [comment]
Decided on sherpa/liberation-sans-regular-subset-numeric-degrees.js at developer meeting.

**Comment by jonathanolson** [comment]
Moved to sherpa, closing.
