### ISSUE TITLE
should GeometryConfiguration inherit Object?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#74]
...similar to how Bond inherits Object. This is a convention that PhET adopted (typically for model types), just wondering if there's something about GeometryConfiguration that makes the convention unnecessary/undesirable.

**Comment by jonathanolson** [comment]
There's nothing that makes it unnecessary/undesirable, however it seems unnecessary?

I'm happy to add an empty inherit( Object, GeometryConfiguration ) if it helps for consistency, but I thought we were only inheriting Object when we wanted to add something to the prototype. Here the prototype is completely unneeded.

Let me know.

**Comment by pixelzoom** [comment]
Sounds good, closing.
