### ISSUE TITLE
why does Molecule extend AXON.Events?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#76]
Seems like a strange type hierarchy. Why use subtyping instead of composition?  If you leave it this way, you might want to explain a bit in the doc.

**Comment by jonathanolson** [comment]
It seems natural to say molecule.on( 'bondAdded', ... ) instead of molecule.events.on( 'bondAdded', ... ), just like how PropertySet extends Events, and how Node mixes in Events.

Added a bit of documentation, let me know if anything else is needed.

**Comment by jonathanolson** [comment]
Also for rationale: anything that wants to emit events and have listeners can mix-in (or directly extend) Events. They both need the super-call in the constructor, and it just seems more convenient.
