### ISSUE TITLE
dead code in Molecule

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#77]
Dead code at line 74:

>     // abstract {LocalShape} getLocalShape( atom )
    // abstract {number | undefined} getMaximumBondLength()
    // abstract {boolean} isReal

**Comment by jonathanolson** [comment]
I've added documentation. I don't agree with passing in the constructor, since it should be on the prototype (we don't want different copies of each function on each Molecule). If desired, I could add in stubs that throw errors when called (let me know).

**Comment by pixelzoom** [comment]
Documentation looks good.

Adding stubs for abstract functions sounds like a good idea for production code, and a Google search found a number of advocates for that approach.  I'll leave it up to you - either add them or not, then close this issue.
