### ISSUE TITLE
more doc in MoleculeShapesColors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#89]
MoleculeShapesColors creates a bunch of object literals, which have one or more of these properties: default, basics, projector.  Pretty sure I know what these 3 properties are, but someone new to the code might not, so doc would be nice.  What I don't know (without rooting around in code) is what happens when a 'color' object is missing one of these properties. Which ones are required? What happens when one is missing?...

**Comment by jonathanolson** [comment]
Let me know if the changes are sufficient.

**Comment by pixelzoom** [comment]
Looks good, closing.
