### ISSUE TITLE
documentation for TitledPanel and MoleculeShapesPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#90]
TitledPanel and its subtype MoleculeShapesPanel both have identical documentation:

> A panel with a title on the top, that relies on a consistent background color.

This doesn't tell me much, and is mostly confusing. Documentation should indicate:

How are they different?
What does "relies on a consistent background color" mean?
Why doesn't TitlePanel extend sun.Panel? (If it's "missing features", should sun.Panel be enhanced?)

**Comment by jonathanolson** [comment]
Added documentation, let me know if anything else is needed.
