### ISSUE TITLE
performance of 'Projector Mode' check box

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#97]
Mac OS X 10.9.5, with Chrome 39, Safari 7.1, Firefox 34. (Did not check on iPad or Windows.)

In the Options dialog, click the 'Projector Mode' check box. There's a significant lag between when the state of the check box toggles. This lag is not present with the 'Show Outer Lone Pairs' check box.

**Comment by jonathanolson** [comment]
Approximately 85% of the cost is in BondGroupNode's getBondDataURL. Of that 56% is cloning three.js geometry, and 38% is rendering + toDataURL().

I'm not particularly sure why it would need to clone the geometry again, since it is using the same renderer (it looks like LocalGeometry shows it is treating it as a new renderer every time).

**Comment by jonathanolson** [comment]
https://github.com/phetsims/molecule-shapes/commit/728fe0c73bafce67266a5defe038a92850844f0a should solve the majority of the performance issue (at least 56%), and in practice seems to solve almost all of it. I'll need to test on the iPad.

Our API stub for our MoleculeShapesScreenView was including a new empty object as a 'renderer' each time, causing Local* to cache new copies each time a stub was needed. This significantly increased the amount of memory used AND the time needed to copy geometries.

**Comment by jonathanolson** [comment]
Unable to test until https://github.com/phetsims/joist/issues/200 is resolved.

**Comment by jonathanolson** [comment]
It's approximately 3 times faster on the iPad than the previous dev version, and much snappier on desktop.

Now the dominant factor is the render() toDataURL() and three.js setSize(), none of which we have direct control over. Any further gains would involve caching/precomputing the images for the available color profiles (slightly longer startup time if we precompute, but the switch should be much faster).

**Comment by jonathanolson** [comment]
Will reopen if necessary, it's much better now.
