### ISSUE TITLE
molecules not rendered in screen icons (Safari 7.1)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/molecule-shapes#98]
See screenshots below. On Mac OS 10.9.5 + Safari 7.1 (9537.85.10.17.1) the molecules in the screen icons (home screen and navbar) are not rendered. Labels on atoms are rendered, see navbar. WebGL is enabled.

![screenshot_408](https://cloud.githubusercontent.com/assets/3046552/5255125/7929f7ea-7975-11e4-82e1-9068a84f11a2.png)
![screenshot_409](https://cloud.githubusercontent.com/assets/3046552/5255129/8c086036-7975-11e4-9619-7a00f5e6da38.png)

**Comment by jonathanolson** [comment]
I've noticed this again, mostly on Safari (mobile/desktop).

**Comment by jonathanolson** [comment]
Looks like we're not handling the general "Safari doesn't immediately set dimensions on HTMLImageElements from a data URL" issue, and Scenery's Image is probably setting the dimensions displayed to 0x0:
![screen shot 2015-01-29 at 10 20 09 am](https://cloud.githubusercontent.com/assets/480878/5962345/82172a72-a7a0-11e4-8aa1-d015156b0b87.png)

**Comment by jonathanolson** [comment]
There is still a slight delay in the display of the images. Recommended at developer meeting to add a way to override an Image's width/height initially for faster display. Pending, @samreid wants to discuss options.

**Comment by samreid** [comment]
My main question was:

Can we just wait until the images have been loaded and have nonzero dimensions before calling the Image.js constructor?  That pattern has served us well elsewhere and I'm not sure why that pattern can't be applied here.

**Comment by samreid** [comment]
To elaborate: doing what I said above may mean deferring part of the sim initialization until the callback from toImage has completed.

**Comment by jonathanolson** [comment]
How would you propose that be done? Additionally, I don't think it handles the case where we create images that are NOT at sim startup.

**Comment by samreid** [comment]
> How would you propose that be done?

Change:

```js
  SimLauncher.launch( function() {
    var sim = new Sim( simTitle, [
      new ModelMoleculesScreen( isBasicsVersion ),
      new RealMoleculesScreen( isBasicsVersion )
    ], simOptions );
    sim.start();
  } );
```

to

```js
  SimLauncher.launch( function() {
    createScreenIcon1().toImage( function( screenIcon1 ) {
      createScreenIcon2().toImage( function( screenIcon2 ) {
        var sim = new Sim( simTitle, [
          new ModelMoleculesScreen( isBasicsVersion, screenIcon1 ),
          new RealMoleculesScreen( isBasicsVersion, screenIcon2 )
        ], simOptions );
        sim.start();
      } );
    } );
```

To handle cases where the image *must* be created dynamically, don't create the scenery.Image or add it to the scene graph until the image data has been delivered by the callback (though perhaps this is tricky for certain framework API situations).

**Comment by jonathanolson** [comment]
That seems like the best approach for images where we don't know the dimensions. I'm just not sure of the advantages of this approach compared to adding 2 parameters to Image when you know for sure the size of the Image (since you have no delay in that case, whereas the above example will take longer to load the sim).

**Comment by samreid** [comment]
I would be fine to add the two parameters to the image constructor, just wanted to make sure everyone understood the alternative I was proposing. Though I am also a little concerned that the images will still be blank for many milliseconds after the same starts up before they appear.   If that is indeed a problem, would t it still be preferable to delaying the start up time?

**Comment by samreid** [comment]
And just to clarify, we are talking about adding options, right? Not about adding more parameters.

**Comment by jonathanolson** [comment]
Yes, was discussing adding options, but they would presumably be getters/setters, etc.

I will have to see if they are still blank.

**Comment by jonathanolson** [comment]
Tested, and it makes the images appear immediately.
