### ISSUE TITLE
Dependency is causing no animation in 2nd screen

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/molecule-shapes#99]
Rolled molecule-shapes back to previous dev version and there is no problem.

**Comment by jonathanolson** [comment]
It's also only when the "Real" mode is checked. "Model" mode on the 2nd screen works fine.

**Comment by jonathanolson** [comment]
Also isolated to the model (the view is displaying correctly, the model locations seem frozen)

**Comment by jonathanolson** [comment]
Joist/Scenery 0.1 also have the problem (after working around the AriaSpeech backwards incompatibility).

**Comment by jonathanolson** [comment]
Verified that the problem goes away with checkout-shas for 1.0.0-dev.12 with molecule-shapes on HEAD.

**Comment by jonathanolson** [comment]
Going from SHAs back to master one repo at a time in the least-breaking order shows axon->master causes the anticipated break.

**Comment by jonathanolson** [comment]
Git bisect shows we break after https://github.com/phetsims/axon/commit/0e90b100b431589f1180b40a9ac58a7045b7ca19

**Comment by jonathanolson** [comment]
PropertySet constructor overwrites the id of the PairGroup, since this is the order of execution:
```js
    // unique identifier
    this.id = nextId++;

    PropertySet.call( this, {
      position: position,
      velocity: Vector3.ZERO,
      userControlled: false
    } );
```

**Comment by samreid** [comment]
Fixed above, animation is working again.  Reassigned to @jonathanolson for review.

**Comment by jonathanolson** [comment]
Looks great, thanks!
